// @generated by schema-rust-next

pub type Text = String;
pub type Integer = u64;
pub type Boolean = bool;

pub use marker_core::schema::mail::DatabaseMarker as DatabaseMarker;
pub use marker_core::schema::mail::CommitSequence as CommitSequence;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum NotaDecodeError {
    Parse(String),
    ExpectedSingleRoot { found: usize },
    ExpectedDelimited { type_name: &'static str, delimiter: &'static str },
    ExpectedRootCount { type_name: &'static str, expected: usize, found: usize },
    ExpectedAtom { type_name: &'static str },
    UnknownVariant { enum_name: &'static str, variant: String },
    InvalidInteger { value: String },
}

impl std::fmt::Display for NotaDecodeError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Parse(error) => write!(formatter, "{error}"),
            Self::ExpectedSingleRoot { found } => write!(formatter, "expected exactly one NOTA root object, found {found}"),
            Self::ExpectedDelimited { type_name, delimiter } => write!(formatter, "expected {type_name} to be a {delimiter} block"),
            Self::ExpectedRootCount { type_name, expected, found } => write!(formatter, "expected {type_name} to hold {expected} root objects, found {found}"),
            Self::ExpectedAtom { type_name } => write!(formatter, "expected {type_name} atom"),
            Self::UnknownVariant { enum_name, variant } => write!(formatter, "unknown {enum_name} variant {variant}"),
            Self::InvalidInteger { value } => write!(formatter, "invalid integer {value}"),
        }
    }
}

impl std::error::Error for NotaDecodeError {}

pub struct NotaSource<'a> {
    source: &'a str,
}

impl<'a> NotaSource<'a> {
    pub fn new(source: &'a str) -> Self {
        Self { source }
    }

    pub fn parse_root(&self) -> Result<nota_next::Block, NotaDecodeError> {
        let document = nota_next::Document::parse(self.source).map_err(|error| NotaDecodeError::Parse(error.to_string()))?;
        if document.holds_root_objects() != 1 {
            return Err(NotaDecodeError::ExpectedSingleRoot { found: document.holds_root_objects() });
        }
        Ok(document.root_object_at(0).expect("root count checked").clone())
    }
}

pub struct NotaBlock<'a> {
    block: &'a nota_next::Block,
}

impl<'a> NotaBlock<'a> {
    pub fn new(block: &'a nota_next::Block) -> Self {
        Self { block }
    }

    pub fn expect_children(
        &self,
        delimiter: nota_next::Delimiter,
        delimiter_name: &'static str,
        type_name: &'static str,
        expected: usize,
    ) -> Result<&'a [nota_next::Block], NotaDecodeError> {
        match self.block {
            nota_next::Block::Delimited { delimiter: found, root_objects, .. } if *found == delimiter => {
                if root_objects.len() != expected {
                    return Err(NotaDecodeError::ExpectedRootCount { type_name, expected, found: root_objects.len() });
                }
                Ok(root_objects)
            }
            _ => Err(NotaDecodeError::ExpectedDelimited { type_name, delimiter: delimiter_name }),
        }
    }

    pub fn parse_text(&self) -> Result<Text, NotaDecodeError> {
        if let Some(text) = self.block.demote_to_string() {
            return Ok(text.to_owned());
        }
        match self.block {
            nota_next::Block::Delimited { delimiter: nota_next::Delimiter::SquareBracket, root_objects, .. } => {
                root_objects.iter().map(|block| NotaBlock::new(block).parse_text()).collect::<Result<Vec<_>, _>>().map(|parts| parts.join(" "))
            }
            _ => Err(NotaDecodeError::ExpectedDelimited { type_name: "Text", delimiter: "text atom or square bracket" }),
        }
    }

    pub fn parse_integer(&self) -> Result<Integer, NotaDecodeError> {
        let value = self.block.demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "Integer" })?;
        value.parse::<Integer>().map_err(|_| NotaDecodeError::InvalidInteger { value: value.to_owned() })
    }

    pub fn parse_boolean(&self) -> Result<Boolean, NotaDecodeError> {
        let value = self.block.demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "Boolean" })?;
        match value {
            "True" => Ok(true),
            "False" => Ok(false),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "Boolean", variant: other.to_owned() }),
        }
    }
}

pub struct NotaText<'a> {
    value: &'a str,
}

impl<'a> NotaText<'a> {
    pub fn new(value: &'a str) -> Self {
        Self { value }
    }

    pub fn format(&self) -> String {
        if self.value.contains("|]") {
            format!("[{}]", self.value.replace(']', " ]"))
        } else if self.value.chars().any(|character| matches!(character, '[' | ']' | '(' | ')' | '{' | '}' | ';' | '\n')) {
            format!("[|{}|]", self.value)
        } else {
            format!("[{}]", self.value)
        }
    }
}

impl From<marker_core::schema::mail::NotaDecodeError> for NotaDecodeError {
    fn from(error: marker_core::schema::mail::NotaDecodeError) -> Self {
        Self::Parse(error.to_string())
    }
}

pub struct NotaCollection<'a> {
    block: &'a nota_next::Block,
}

impl<'a> NotaCollection<'a> {
    pub fn new(block: &'a nota_next::Block) -> Self {
        Self { block }
    }

    pub fn parse_vector<Element, Parse>(&self, parse: Parse) -> Result<Vec<Element>, NotaDecodeError>
    where
        Parse: FnMut(&nota_next::Block) -> Result<Element, NotaDecodeError>,
    {
        match self.block {
            nota_next::Block::Delimited { delimiter: nota_next::Delimiter::SquareBracket, root_objects, .. } => {
                root_objects.iter().map(parse).collect()
            }
            _ => Err(NotaDecodeError::ExpectedDelimited { type_name: "Vec", delimiter: "square bracket" }),
        }
    }

    pub fn parse_map<Key, Value, ParseKey, ParseValue>(&self, mut parse_key: ParseKey, mut parse_value: ParseValue) -> Result<std::collections::BTreeMap<Key, Value>, NotaDecodeError>
    where
        Key: Ord,
        ParseKey: FnMut(&nota_next::Block) -> Result<Key, NotaDecodeError>,
        ParseValue: FnMut(&nota_next::Block) -> Result<Value, NotaDecodeError>,
    {
        match self.block {
            nota_next::Block::Delimited { delimiter: nota_next::Delimiter::Brace, root_objects, .. } => {
                if root_objects.len() % 2 != 0 {
                    return Err(NotaDecodeError::ExpectedRootCount { type_name: "BTreeMap", expected: root_objects.len() + 1, found: root_objects.len() });
                }
                let mut map = std::collections::BTreeMap::new();
                let mut index = 0;
                while index < root_objects.len() {
                    let key = parse_key(&root_objects[index])?;
                    let value = parse_value(&root_objects[index + 1])?;
                    map.insert(key, value);
                    index += 2;
                }
                Ok(map)
            }
            _ => Err(NotaDecodeError::ExpectedDelimited { type_name: "BTreeMap", delimiter: "brace" }),
        }
    }

    pub fn parse_option<Inner, Parse>(&self, mut parse: Parse) -> Result<Option<Inner>, NotaDecodeError>
    where
        Parse: FnMut(&nota_next::Block) -> Result<Inner, NotaDecodeError>,
    {
        if self.block.demote_to_string() == Some("None") {
            return Ok(None);
        }
        let children = NotaBlock::new(self.block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Option", 2)?;
        let tag = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "Option tag" })?;
        if tag != "Some" {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "Option", variant: tag.to_owned() });
        }
        Ok(Some(parse(&children[1])?))
    }

    pub fn format_vector<Element, Format>(elements: &[Element], format: Format) -> String
    where
        Format: FnMut(&Element) -> String,
    {
        let parts: Vec<String> = elements.iter().map(format).collect();
        format!("[{}]", parts.join(" "))
    }

    pub fn format_map<Key, Value, FormatKey, FormatValue>(map: &std::collections::BTreeMap<Key, Value>, mut format_key: FormatKey, mut format_value: FormatValue) -> String
    where
        FormatKey: FnMut(&Key) -> String,
        FormatValue: FnMut(&Value) -> String,
    {
        let mut parts: Vec<String> = Vec::new();
        for (key, value) in map {
            parts.push(format_key(key));
            parts.push(format_value(value));
        }
        format!("{{{}}}", parts.join(" "))
    }

    pub fn format_option<Inner, Format>(value: &Option<Inner>, mut format: Format) -> String
    where
        Format: FnMut(&Inner) -> String,
    {
        match value {
            Some(inner) => format!("(Some {})", format(inner)),
            None => "None".to_owned(),
        }
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
#[rkyv(derive(PartialEq, Eq, PartialOrd, Ord))]
pub struct Topic(pub Text);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Topics(pub Vec<Topic>);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Description(pub Text);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentName(pub Text);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordIdentifier(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rejection(pub Description);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    pub topics: Topics,
    pub description: Description,
    pub agent_name: AgentName,
    pub database_marker: DatabaseMarker,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query {
    pub topics: Topics,
    pub limit: Option<Integer>,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordReceipt {
    pub record_identifier: RecordIdentifier,
    pub database_marker: DatabaseMarker,
    pub commit_sequence: CommitSequence,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordSet {
    pub records: Vec<Entry>,
    pub by_topic: std::collections::BTreeMap<Topic, RecordIdentifier>,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Record(Entry),
    Observe(Query),
    Mark(DatabaseMarker),
    Commit(CommitSequence),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Recorded(RecordReceipt),
    Observed(RecordSet),
    Marked(DatabaseMarker),
    Committed(CommitSequence),
    Rejected(Rejection),
}

impl Topic {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_text()?))
    }

    pub fn to_nota(&self) -> String {
        NotaText::new(&self.0).format()
    }
}

impl Topics {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaCollection::new(block).parse_vector(Topic::from_nota_block)?))
    }

    pub fn to_nota(&self) -> String {
        NotaCollection::format_vector(&self.0, |element| element.to_nota())
    }
}

impl Description {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_text()?))
    }

    pub fn to_nota(&self) -> String {
        NotaText::new(&self.0).format()
    }
}

impl AgentName {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_text()?))
    }

    pub fn to_nota(&self) -> String {
        NotaText::new(&self.0).format()
    }
}

impl RecordIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_integer()?))
    }

    pub fn to_nota(&self) -> String {
        self.0.to_string()
    }
}

impl Rejection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(Description::from_nota_block(block)?))
    }

    pub fn to_nota(&self) -> String {
        self.0.to_nota()
    }
}

impl Entry {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Entry", 4)?;
        Ok(Self {
            topics: Topics::from_nota_block(&children[0])?,
            description: Description::from_nota_block(&children[1])?,
            agent_name: AgentName::from_nota_block(&children[2])?,
            database_marker: DatabaseMarker::from_nota_block(&children[3])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.topics.to_nota(),
            self.description.to_nota(),
            self.agent_name.to_nota(),
            self.database_marker.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl Query {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Query", 2)?;
        Ok(Self {
            topics: Topics::from_nota_block(&children[0])?,
            limit: NotaCollection::new(&children[1]).parse_option(|inner_block| NotaBlock::new(inner_block).parse_integer())?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.topics.to_nota(),
            NotaCollection::format_option(&self.limit, |inner| inner.to_string()),
        ];
        format!("({})", fields.join(" "))
    }
}

impl RecordReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "RecordReceipt", 3)?;
        Ok(Self {
            record_identifier: RecordIdentifier::from_nota_block(&children[0])?,
            database_marker: DatabaseMarker::from_nota_block(&children[1])?,
            commit_sequence: CommitSequence::from_nota_block(&children[2])?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            self.record_identifier.to_nota(),
            self.database_marker.to_nota(),
            self.commit_sequence.to_nota(),
        ];
        format!("({})", fields.join(" "))
    }
}

impl RecordSet {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "RecordSet", 2)?;
        Ok(Self {
            records: NotaCollection::new(&children[0]).parse_vector(Entry::from_nota_block)?,
            by_topic: NotaCollection::new(&children[1]).parse_map(Topic::from_nota_block, RecordIdentifier::from_nota_block)?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            NotaCollection::format_vector(&self.records, |element| element.to_nota()),
            NotaCollection::format_map(&self.by_topic, |key| key.to_nota(), |value| value.to_nota()),
        ];
        format!("({})", fields.join(" "))
    }
}

impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "Input", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Input", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Record" => Ok(Self::Record(Entry::from_nota_block(&children[1])?)),
            "Observe" => Ok(Self::Observe(Query::from_nota_block(&children[1])?)),
            "Mark" => Ok(Self::Mark(DatabaseMarker::from_nota_block(&children[1])?)),
            "Commit" => Ok(Self::Commit(CommitSequence::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "Input", variant: other.to_owned() }),
        }
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Record(payload) => format!("(Record {})", payload.to_nota()),
            Self::Observe(payload) => format!("(Observe {})", payload.to_nota()),
            Self::Mark(payload) => format!("(Mark {})", payload.to_nota()),
            Self::Commit(payload) => format!("(Commit {})", payload.to_nota()),
        }
    }
}

impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        let root = NotaSource::new(source).parse_root()?;
        Self::from_nota_block(&root)
    }
}

impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.to_nota())
    }
}

impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "Output", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Output", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Recorded" => Ok(Self::Recorded(RecordReceipt::from_nota_block(&children[1])?)),
            "Observed" => Ok(Self::Observed(RecordSet::from_nota_block(&children[1])?)),
            "Marked" => Ok(Self::Marked(DatabaseMarker::from_nota_block(&children[1])?)),
            "Committed" => Ok(Self::Committed(CommitSequence::from_nota_block(&children[1])?)),
            "Rejected" => Ok(Self::Rejected(Rejection::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "Output", variant: other.to_owned() }),
        }
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Recorded(payload) => format!("(Recorded {})", payload.to_nota()),
            Self::Observed(payload) => format!("(Observed {})", payload.to_nota()),
            Self::Marked(payload) => format!("(Marked {})", payload.to_nota()),
            Self::Committed(payload) => format!("(Committed {})", payload.to_nota()),
            Self::Rejected(payload) => format!("(Rejected {})", payload.to_nota()),
        }
    }
}

impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        let root = NotaSource::new(source).parse_root()?;
        Self::from_nota_block(&root)
    }
}

impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.to_nota())
    }
}

pub mod short_header {
    pub const INPUT_RECORD: u64 = 0x0000000000000000;
    pub const INPUT_OBSERVE: u64 = 0x0001000000000000;
    pub const INPUT_MARK: u64 = 0x0002000000000000;
    pub const INPUT_COMMIT: u64 = 0x0003000000000000;
    pub const OUTPUT_RECORDED: u64 = 0x0100000000000000;
    pub const OUTPUT_OBSERVED: u64 = 0x0101000000000000;
    pub const OUTPUT_MARKED: u64 = 0x0102000000000000;
    pub const OUTPUT_COMMITTED: u64 = 0x0103000000000000;
    pub const OUTPUT_REJECTED: u64 = 0x0104000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InputRoute {
    Record,
    Observe,
    Mark,
    Commit,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OutputRoute {
    Recorded,
    Observed,
    Marked,
    Committed,
    Rejected,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Record(_) => InputRoute::Record,
            Self::Observe(_) => InputRoute::Observe,
            Self::Mark(_) => InputRoute::Mark,
            Self::Commit(_) => InputRoute::Commit,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Record(_) => short_header::INPUT_RECORD,
            Self::Observe(_) => short_header::INPUT_OBSERVE,
            Self::Mark(_) => short_header::INPUT_MARK,
            Self::Commit(_) => short_header::INPUT_COMMIT,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_RECORD => Ok(InputRoute::Record),
            short_header::INPUT_OBSERVE => Ok(InputRoute::Observe),
            short_header::INPUT_MARK => Ok(InputRoute::Mark),
            short_header::INPUT_COMMIT => Ok(InputRoute::Commit),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Recorded(_) => OutputRoute::Recorded,
            Self::Observed(_) => OutputRoute::Observed,
            Self::Marked(_) => OutputRoute::Marked,
            Self::Committed(_) => OutputRoute::Committed,
            Self::Rejected(_) => OutputRoute::Rejected,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Recorded(_) => short_header::OUTPUT_RECORDED,
            Self::Observed(_) => short_header::OUTPUT_OBSERVED,
            Self::Marked(_) => short_header::OUTPUT_MARKED,
            Self::Committed(_) => short_header::OUTPUT_COMMITTED,
            Self::Rejected(_) => short_header::OUTPUT_REJECTED,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_RECORDED => Ok(OutputRoute::Recorded),
            short_header::OUTPUT_OBSERVED => Ok(OutputRoute::Observed),
            short_header::OUTPUT_MARKED => Ok(OutputRoute::Marked),
            short_header::OUTPUT_COMMITTED => Ok(OutputRoute::Committed),
            short_header::OUTPUT_REJECTED => Ok(OutputRoute::Rejected),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct MessageIdentifier(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct OriginRoute(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum MessageRoot {
    Input,
    Output,
}

pub mod schema {
    #[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
    pub enum Plane<SignalRoot, NexusRoot, SemaRoot> {
        Signal(super::Signal<SignalRoot>),
        Nexus(super::Nexus<NexusRoot>),
        Sema(super::Sema<SemaRoot>),
    }

    impl<SignalRoot, NexusRoot, SemaRoot> Plane<SignalRoot, NexusRoot, SemaRoot> {
        pub fn origin_route(&self) -> super::OriginRoute {
            match self {
                Self::Signal(message) => message.origin_route(),
                Self::Nexus(message) => message.origin_route(),
                Self::Sema(message) => message.origin_route(),
            }
        }
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Signal<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Signal<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Signal<NextRoot> {
        Signal::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSent {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub root: MessageRoot,
    pub short_header: Integer,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NexusMail<Payload> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub payload: Payload,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageProcessed<Reply> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub reply: Reply,
}

pub trait MessageSentHook {
    type Error;

    fn message_sent(&mut self, event: MessageSent) -> Result<(), Self::Error>;
}

pub trait MessageProcessedHook<Reply> {
    type Error;

    fn message_processed(&mut self, event: MessageProcessed<Reply>) -> Result<(), Self::Error>;
}

impl MessageSent {
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageSentHook,
    {
        hook.message_sent(self.clone())
    }
}

impl<Payload> NexusMail<Payload> {
    pub fn new(identifier: MessageIdentifier, origin_route: OriginRoute, payload: Payload) -> Self {
        Self { identifier, origin_route, payload }
    }

    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn into_payload(self) -> Payload {
        self.payload
    }
}

impl<Reply> MessageProcessed<Reply> {
    pub fn new(identifier: MessageIdentifier, origin_route: OriginRoute, reply: Reply) -> Self {
        Self { identifier, origin_route, reply }
    }

    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn into_reply(self) -> Reply {
        self.reply
    }

    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageProcessedHook<Reply>,
        Reply: Clone,
    {
        hook.message_processed(self.clone())
    }
}

impl Input {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }

}

impl signal::Signal<Input> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Input,
            short_header: self.root().short_header(),
        }
    }
}

impl Output {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }

}

impl signal::Signal<Output> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Output,
            short_header: self.root().short_header(),
        }
    }
}

pub mod signal {
    pub type Input = super::Input;
    pub type Output = super::Output;
    pub type Signal<Root> = super::Signal<Root>;
}

impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_integer()?))
    }

    pub fn to_nota(self) -> String {
        self.0.to_string()
    }
}

pub trait InputNexus {
    type Reply;
    type Error;

    fn record(&self, mail: NexusMail<Entry>) -> Result<Self::Reply, Self::Error>;
    fn observe(&self, mail: NexusMail<Query>) -> Result<Self::Reply, Self::Error>;
    fn mark(&self, mail: NexusMail<DatabaseMarker>) -> Result<Self::Reply, Self::Error>;
    fn commit(&self, mail: NexusMail<CommitSequence>) -> Result<Self::Reply, Self::Error>;
}

impl Input {
    pub fn dispatch_mail_with_nexus<NexusActor>(self, identifier: MessageIdentifier, origin_route: OriginRoute, nexus: &NexusActor) -> Result<MessageProcessed<NexusActor::Reply>, NexusActor::Error>
    where
        NexusActor: InputNexus,
    {
        let reply = match self {
            Self::Record(payload) => nexus.record(NexusMail::new(identifier, origin_route, payload)),
            Self::Observe(payload) => nexus.observe(NexusMail::new(identifier, origin_route, payload)),
            Self::Mark(payload) => nexus.mark(NexusMail::new(identifier, origin_route, payload)),
            Self::Commit(payload) => nexus.commit(NexusMail::new(identifier, origin_route, payload)),
        }?;
        Ok(MessageProcessed::new(identifier, origin_route, reply))
    }
}

pub trait OutputNexus {
    type Reply;
    type Error;

    fn recorded(&self, mail: NexusMail<RecordReceipt>) -> Result<Self::Reply, Self::Error>;
    fn observed(&self, mail: NexusMail<RecordSet>) -> Result<Self::Reply, Self::Error>;
    fn marked(&self, mail: NexusMail<DatabaseMarker>) -> Result<Self::Reply, Self::Error>;
    fn committed(&self, mail: NexusMail<CommitSequence>) -> Result<Self::Reply, Self::Error>;
    fn rejected(&self, mail: NexusMail<Rejection>) -> Result<Self::Reply, Self::Error>;
}

impl Output {
    pub fn dispatch_mail_with_nexus<NexusActor>(self, identifier: MessageIdentifier, origin_route: OriginRoute, nexus: &NexusActor) -> Result<MessageProcessed<NexusActor::Reply>, NexusActor::Error>
    where
        NexusActor: OutputNexus,
    {
        let reply = match self {
            Self::Recorded(payload) => nexus.recorded(NexusMail::new(identifier, origin_route, payload)),
            Self::Observed(payload) => nexus.observed(NexusMail::new(identifier, origin_route, payload)),
            Self::Marked(payload) => nexus.marked(NexusMail::new(identifier, origin_route, payload)),
            Self::Committed(payload) => nexus.committed(NexusMail::new(identifier, origin_route, payload)),
            Self::Rejected(payload) => nexus.rejected(NexusMail::new(identifier, origin_route, payload)),
        }?;
        Ok(MessageProcessed::new(identifier, origin_route, reply))
    }
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;

    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}

pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}

impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}
