// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

#[cfg(feature = "nota-text")]
pub use nota_next::{
    NotaDecode, NotaDecodeError, NotaEncode, NotaSource,
};

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
#[rkyv(derive(PartialEq, Eq, PartialOrd, Ord))]
pub struct Topic(pub String);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Topics(pub Vec<Topic>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Description(pub String);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentName(pub String);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Timestamp(pub Integer);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordIdentifier(pub Integer);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionToken(pub Integer);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommitSequence(pub Integer);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DatabaseDigest(pub Integer);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Magnitude {
    Minimum,
    VeryLow,
    Low,
    Medium,
    High,
    VeryHigh,
    Maximum,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Kind {
    Decision,
    Principle,
    Correction,
    Clarification,
    Constraint,
    Observation,
    Question,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RejectionReason {
    Malformed,
    Unauthorized,
    Conflict,
    Unsupported,
    StaleVersion,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    pub topics: Topics,
    pub kind: Kind,
    pub description: Description,
    pub magnitude: Magnitude,
    pub agent_name: AgentName,
    pub timestamp: Timestamp,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Correction {
    pub record_identifier: RecordIdentifier,
    pub description: Description,
    pub magnitude: Magnitude,
    pub agent_name: AgentName,
    pub timestamp: Timestamp,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query {
    pub topics: Topics,
    pub kinds: Vec<Kind>,
    pub limit: Option<Integer>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WatchRequest {
    pub topics: Topics,
    pub kinds: Vec<Kind>,
    pub agent_name: AgentName,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordReceipt {
    pub record_identifier: RecordIdentifier,
    pub commit_sequence: CommitSequence,
    pub database_digest: DatabaseDigest,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CorrectionReceipt {
    pub record_identifier: RecordIdentifier,
    pub commit_sequence: CommitSequence,
    pub database_digest: DatabaseDigest,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordSet {
    pub records: Vec<Entry>,
    pub by_topic: std::collections::BTreeMap<Topic, RecordIdentifier>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubscriptionReceipt {
    pub subscription_token: SubscriptionToken,
    pub commit_sequence: CommitSequence,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rejection {
    pub rejection_reason: RejectionReason,
    pub description: Description,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IndexReceipt {
    pub commit_sequence: CommitSequence,
    pub database_digest: DatabaseDigest,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Record(Entry),
    Correct(Correction),
    Observe(Query),
    Watch(WatchRequest),
    Unwatch(SubscriptionToken),
    Reindex,
    Compact,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Recorded(RecordReceipt),
    Corrected(CorrectionReceipt),
    Observed(RecordSet),
    Watching(SubscriptionReceipt),
    Unwatched(SubscriptionReceipt),
    Rejected(Rejection),
    Indexed(IndexReceipt),
}

impl From<Entry> for Input {
    fn from(payload: Entry) -> Self {
        Self::Record(payload)
    }
}

impl From<Correction> for Input {
    fn from(payload: Correction) -> Self {
        Self::Correct(payload)
    }
}

impl From<Query> for Input {
    fn from(payload: Query) -> Self {
        Self::Observe(payload)
    }
}

impl From<WatchRequest> for Input {
    fn from(payload: WatchRequest) -> Self {
        Self::Watch(payload)
    }
}

impl From<SubscriptionToken> for Input {
    fn from(payload: SubscriptionToken) -> Self {
        Self::Unwatch(payload)
    }
}

impl From<RecordReceipt> for Output {
    fn from(payload: RecordReceipt) -> Self {
        Self::Recorded(payload)
    }
}

impl From<CorrectionReceipt> for Output {
    fn from(payload: CorrectionReceipt) -> Self {
        Self::Corrected(payload)
    }
}

impl From<RecordSet> for Output {
    fn from(payload: RecordSet) -> Self {
        Self::Observed(payload)
    }
}

impl From<Rejection> for Output {
    fn from(payload: Rejection) -> Self {
        Self::Rejected(payload)
    }
}

impl From<IndexReceipt> for Output {
    fn from(payload: IndexReceipt) -> Self {
        Self::Indexed(payload)
    }
}

#[cfg(feature = "nota-text")]
impl Topic {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Topics {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Description {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl AgentName {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Timestamp {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RecordIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SubscriptionToken {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CommitSequence {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DatabaseDigest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Magnitude {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Kind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Entry {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Correction {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Query {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl WatchRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RecordReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CorrectionReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RecordSet {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SubscriptionReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Rejection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl IndexReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_RECORD: u64 = 0x0000000000000000;
    pub const INPUT_CORRECT: u64 = 0x0001000000000000;
    pub const INPUT_OBSERVE: u64 = 0x0002000000000000;
    pub const INPUT_WATCH: u64 = 0x0003000000000000;
    pub const INPUT_UNWATCH: u64 = 0x0004000000000000;
    pub const INPUT_REINDEX: u64 = 0x0005000000000000;
    pub const INPUT_COMPACT: u64 = 0x0006000000000000;
    pub const OUTPUT_RECORDED: u64 = 0x0100000000000000;
    pub const OUTPUT_CORRECTED: u64 = 0x0101000000000000;
    pub const OUTPUT_OBSERVED: u64 = 0x0102000000000000;
    pub const OUTPUT_WATCHING: u64 = 0x0103000000000000;
    pub const OUTPUT_UNWATCHED: u64 = 0x0104000000000000;
    pub const OUTPUT_REJECTED: u64 = 0x0105000000000000;
    pub const OUTPUT_INDEXED: u64 = 0x0106000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum InputRoute {
    Record,
    Correct,
    Observe,
    Watch,
    Unwatch,
    Reindex,
    Compact,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum OutputRoute {
    Recorded,
    Corrected,
    Observed,
    Watching,
    Unwatched,
    Rejected,
    Indexed,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Record(_) => InputRoute::Record,
            Self::Correct(_) => InputRoute::Correct,
            Self::Observe(_) => InputRoute::Observe,
            Self::Watch(_) => InputRoute::Watch,
            Self::Unwatch(_) => InputRoute::Unwatch,
            Self::Reindex => InputRoute::Reindex,
            Self::Compact => InputRoute::Compact,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Record(_) => short_header::INPUT_RECORD,
            Self::Correct(_) => short_header::INPUT_CORRECT,
            Self::Observe(_) => short_header::INPUT_OBSERVE,
            Self::Watch(_) => short_header::INPUT_WATCH,
            Self::Unwatch(_) => short_header::INPUT_UNWATCH,
            Self::Reindex => short_header::INPUT_REINDEX,
            Self::Compact => short_header::INPUT_COMPACT,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_RECORD => Ok(InputRoute::Record),
            short_header::INPUT_CORRECT => Ok(InputRoute::Correct),
            short_header::INPUT_OBSERVE => Ok(InputRoute::Observe),
            short_header::INPUT_WATCH => Ok(InputRoute::Watch),
            short_header::INPUT_UNWATCH => Ok(InputRoute::Unwatch),
            short_header::INPUT_REINDEX => Ok(InputRoute::Reindex),
            short_header::INPUT_COMPACT => Ok(InputRoute::Compact),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Recorded(_) => OutputRoute::Recorded,
            Self::Corrected(_) => OutputRoute::Corrected,
            Self::Observed(_) => OutputRoute::Observed,
            Self::Watching(_) => OutputRoute::Watching,
            Self::Unwatched(_) => OutputRoute::Unwatched,
            Self::Rejected(_) => OutputRoute::Rejected,
            Self::Indexed(_) => OutputRoute::Indexed,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Recorded(_) => short_header::OUTPUT_RECORDED,
            Self::Corrected(_) => short_header::OUTPUT_CORRECTED,
            Self::Observed(_) => short_header::OUTPUT_OBSERVED,
            Self::Watching(_) => short_header::OUTPUT_WATCHING,
            Self::Unwatched(_) => short_header::OUTPUT_UNWATCHED,
            Self::Rejected(_) => short_header::OUTPUT_REJECTED,
            Self::Indexed(_) => short_header::OUTPUT_INDEXED,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_RECORDED => Ok(OutputRoute::Recorded),
            short_header::OUTPUT_CORRECTED => Ok(OutputRoute::Corrected),
            short_header::OUTPUT_OBSERVED => Ok(OutputRoute::Observed),
            short_header::OUTPUT_WATCHING => Ok(OutputRoute::Watching),
            short_header::OUTPUT_UNWATCHED => Ok(OutputRoute::Unwatched),
            short_header::OUTPUT_REJECTED => Ok(OutputRoute::Rejected),
            short_header::OUTPUT_INDEXED => Ok(OutputRoute::Indexed),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SignalObjectName {
    Input(InputRoute),
    Output(OutputRoute),
}

impl SignalObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Input(route) => match route {
                InputRoute::Record => "SignalInputRecord",
                InputRoute::Correct => "SignalInputCorrect",
                InputRoute::Observe => "SignalInputObserve",
                InputRoute::Watch => "SignalInputWatch",
                InputRoute::Unwatch => "SignalInputUnwatch",
                InputRoute::Reindex => "SignalInputReindex",
                InputRoute::Compact => "SignalInputCompact",
            },
            Self::Output(route) => match route {
                OutputRoute::Recorded => "SignalOutputRecorded",
                OutputRoute::Corrected => "SignalOutputCorrected",
                OutputRoute::Observed => "SignalOutputObserved",
                OutputRoute::Watching => "SignalOutputWatching",
                OutputRoute::Unwatched => "SignalOutputUnwatched",
                OutputRoute::Rejected => "SignalOutputRejected",
                OutputRoute::Indexed => "SignalOutputIndexed",
            },
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObjectName {
    Signal(SignalObjectName),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct TraceEvent {
    pub object_name: ObjectName,
}

impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Signal(object_name) => object_name.name(),
        }
    }
}

impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self { object_name }
    }

    pub fn object_name(&self) -> ObjectName {
        self.object_name
    }

    pub fn name(&self) -> &'static str {
        self.object_name.name()
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct MessageIdentifier(pub Integer);
#[cfg(feature = "nota-text")]
impl MessageIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct OriginRoute(pub Integer);
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum MessageRoot {
    Input,
    Output,
}

pub mod schema {
    #[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
    pub enum Plane<SignalRoot, NexusRoot, SemaRoot> {
        Signal(super::Signal<SignalRoot>),
        Nexus(super::Nexus<NexusRoot>),
        Sema(super::Sema<SemaRoot>),
    }

    impl<SignalRoot, NexusRoot, SemaRoot> Plane<SignalRoot, NexusRoot, SemaRoot> {
        pub fn origin_route(&self) -> super::OriginRoute {
            match self {
                Self::Signal(message) => message.origin_route(),
                Self::Nexus(message) => message.origin_route(),
                Self::Sema(message) => message.origin_route(),
            }
        }
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Signal<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Signal<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Signal<NextRoot> {
        Signal::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSent {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub root: MessageRoot,
    pub short_header: Integer,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageProcessed<Reply> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub reply: Reply,
}

pub trait MessageSentHook {
    type Error;

    fn message_sent(&mut self, event: MessageSent) -> Result<(), Self::Error>;
}

pub trait MessageProcessedHook<Reply> {
    type Error;

    fn message_processed(&mut self, event: MessageProcessed<Reply>) -> Result<(), Self::Error>;
}

impl MessageSent {
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageSentHook,
    {
        hook.message_sent(self.clone())
    }
}

impl<Reply> MessageProcessed<Reply> {
    pub fn new(identifier: MessageIdentifier, origin_route: OriginRoute, reply: Reply) -> Self {
        Self { identifier, origin_route, reply }
    }

    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn into_reply(self) -> Reply {
        self.reply
    }

    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageProcessedHook<Reply>,
        Reply: Clone,
    {
        hook.message_processed(self.clone())
    }
}

impl Input {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }

}

impl signal::Signal<Input> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Input,
            short_header: self.root().short_header(),
        }
    }
}

impl Output {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }

}

impl signal::Signal<Output> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Output,
            short_header: self.root().short_header(),
        }
    }
}

pub mod signal {
    pub type Input = super::Input;
    pub type Output = super::Output;
    pub type Signal<Root> = super::Signal<Root>;
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;

    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}

pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}

impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}
