// @generated by schema-rust-next

pub type Text = String;
pub type Integer = u64;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum NotaDecodeError {
    Parse(String),
    ExpectedSingleRoot { found: usize },
    ExpectedDelimited { type_name: &'static str, delimiter: &'static str },
    ExpectedRootCount { type_name: &'static str, expected: usize, found: usize },
    ExpectedAtom { type_name: &'static str },
    UnknownVariant { enum_name: &'static str, variant: String },
    InvalidInteger { value: String },
}

impl std::fmt::Display for NotaDecodeError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Parse(error) => write!(formatter, "{error}"),
            Self::ExpectedSingleRoot { found } => write!(formatter, "expected exactly one NOTA root object, found {found}"),
            Self::ExpectedDelimited { type_name, delimiter } => write!(formatter, "expected {type_name} to be a {delimiter} block"),
            Self::ExpectedRootCount { type_name, expected, found } => write!(formatter, "expected {type_name} to hold {expected} root objects, found {found}"),
            Self::ExpectedAtom { type_name } => write!(formatter, "expected {type_name} atom"),
            Self::UnknownVariant { enum_name, variant } => write!(formatter, "unknown {enum_name} variant {variant}"),
            Self::InvalidInteger { value } => write!(formatter, "invalid integer {value}"),
        }
    }
}

impl std::error::Error for NotaDecodeError {}

pub struct NotaSource<'a> {
    source: &'a str,
}

impl<'a> NotaSource<'a> {
    pub fn new(source: &'a str) -> Self {
        Self { source }
    }

    pub fn parse_root(&self) -> Result<nota_next::Block, NotaDecodeError> {
        let document = nota_next::Document::parse(self.source).map_err(|error| NotaDecodeError::Parse(error.to_string()))?;
        if document.holds_root_objects() != 1 {
            return Err(NotaDecodeError::ExpectedSingleRoot { found: document.holds_root_objects() });
        }
        Ok(document.root_object_at(0).expect("root count checked").clone())
    }
}

pub struct NotaBlock<'a> {
    block: &'a nota_next::Block,
}

impl<'a> NotaBlock<'a> {
    pub fn new(block: &'a nota_next::Block) -> Self {
        Self { block }
    }

    pub fn expect_children(
        &self,
        delimiter: nota_next::Delimiter,
        delimiter_name: &'static str,
        type_name: &'static str,
        expected: usize,
    ) -> Result<&'a [nota_next::Block], NotaDecodeError> {
        match self.block {
            nota_next::Block::Delimited { delimiter: found, root_objects, .. } if *found == delimiter => {
                if root_objects.len() != expected {
                    return Err(NotaDecodeError::ExpectedRootCount { type_name, expected, found: root_objects.len() });
                }
                Ok(root_objects)
            }
            _ => Err(NotaDecodeError::ExpectedDelimited { type_name, delimiter: delimiter_name }),
        }
    }

    pub fn parse_text(&self) -> Result<Text, NotaDecodeError> {
        if let Some(text) = self.block.demote_to_string() {
            return Ok(text.to_owned());
        }
        match self.block {
            nota_next::Block::Delimited { delimiter: nota_next::Delimiter::SquareBracket, root_objects, .. } => {
                root_objects.iter().map(|block| NotaBlock::new(block).parse_text()).collect::<Result<Vec<_>, _>>().map(|parts| parts.join(" "))
            }
            _ => Err(NotaDecodeError::ExpectedDelimited { type_name: "Text", delimiter: "text atom or square bracket" }),
        }
    }

    pub fn parse_integer(&self) -> Result<Integer, NotaDecodeError> {
        let value = self.block.demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "Integer" })?;
        value.parse::<Integer>().map_err(|_| NotaDecodeError::InvalidInteger { value: value.to_owned() })
    }
}

pub struct NotaText<'a> {
    value: &'a str,
}

impl<'a> NotaText<'a> {
    pub fn new(value: &'a str) -> Self {
        Self { value }
    }

    pub fn format(&self) -> String {
        if self.value.contains("|]") {
            format!("[{}]", self.value.replace(']', " ]"))
        } else if self.value.chars().any(|character| matches!(character, '[' | ']' | '(' | ')' | '{' | '}' | ';' | '\n')) {
            format!("[|{}|]", self.value)
        } else {
            format!("[{}]", self.value)
        }
    }
}

pub struct NotaCollection<'a> {
    block: &'a nota_next::Block,
}

impl<'a> NotaCollection<'a> {
    pub fn new(block: &'a nota_next::Block) -> Self {
        Self { block }
    }

    pub fn parse_vector<Element, Parse>(&self, parse: Parse) -> Result<Vec<Element>, NotaDecodeError>
    where
        Parse: FnMut(&nota_next::Block) -> Result<Element, NotaDecodeError>,
    {
        match self.block {
            nota_next::Block::Delimited { delimiter: nota_next::Delimiter::SquareBracket, root_objects, .. } => {
                root_objects.iter().map(parse).collect()
            }
            _ => Err(NotaDecodeError::ExpectedDelimited { type_name: "Vec", delimiter: "square bracket" }),
        }
    }

    pub fn parse_map<Key, Value, ParseKey, ParseValue>(&self, mut parse_key: ParseKey, mut parse_value: ParseValue) -> Result<std::collections::BTreeMap<Key, Value>, NotaDecodeError>
    where
        Key: Ord,
        ParseKey: FnMut(&nota_next::Block) -> Result<Key, NotaDecodeError>,
        ParseValue: FnMut(&nota_next::Block) -> Result<Value, NotaDecodeError>,
    {
        match self.block {
            nota_next::Block::Delimited { delimiter: nota_next::Delimiter::Brace, root_objects, .. } => {
                if root_objects.len() % 2 != 0 {
                    return Err(NotaDecodeError::ExpectedRootCount { type_name: "BTreeMap", expected: root_objects.len() + 1, found: root_objects.len() });
                }
                let mut map = std::collections::BTreeMap::new();
                let mut index = 0;
                while index < root_objects.len() {
                    let key = parse_key(&root_objects[index])?;
                    let value = parse_value(&root_objects[index + 1])?;
                    map.insert(key, value);
                    index += 2;
                }
                Ok(map)
            }
            _ => Err(NotaDecodeError::ExpectedDelimited { type_name: "BTreeMap", delimiter: "brace" }),
        }
    }

    pub fn parse_option<Inner, Parse>(&self, mut parse: Parse) -> Result<Option<Inner>, NotaDecodeError>
    where
        Parse: FnMut(&nota_next::Block) -> Result<Inner, NotaDecodeError>,
    {
        if self.block.demote_to_string() == Some("None") {
            return Ok(None);
        }
        let children = NotaBlock::new(self.block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Option", 2)?;
        let tag = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "Option tag" })?;
        if tag != "Some" {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "Option", variant: tag.to_owned() });
        }
        Ok(Some(parse(&children[1])?))
    }

    pub fn format_vector<Element, Format>(elements: &[Element], format: Format) -> String
    where
        Format: FnMut(&Element) -> String,
    {
        let parts: Vec<String> = elements.iter().map(format).collect();
        format!("[{}]", parts.join(" "))
    }

    pub fn format_map<Key, Value, FormatKey, FormatValue>(map: &std::collections::BTreeMap<Key, Value>, mut format_key: FormatKey, mut format_value: FormatValue) -> String
    where
        FormatKey: FnMut(&Key) -> String,
        FormatValue: FnMut(&Value) -> String,
    {
        let mut parts: Vec<String> = Vec::new();
        for (key, value) in map {
            parts.push(format_key(key));
            parts.push(format_value(value));
        }
        format!("{{{}}}", parts.join(" "))
    }

    pub fn format_option<Inner, Format>(value: &Option<Inner>, mut format: Format) -> String
    where
        Format: FnMut(&Inner) -> String,
    {
        match value {
            Some(inner) => format!("(Some {})", format(inner)),
            None => "None".to_owned(),
        }
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
#[rkyv(derive(PartialEq, Eq, PartialOrd, Ord))]
pub struct NodeName(pub Text);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NodeConfig(pub Text);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Service(pub Text);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Cluster {
    pub nodes: std::collections::BTreeMap<NodeName, NodeConfig>,
    pub services: Vec<Service>,
    pub cache: Option<Service>,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Project(Cluster),
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Projected(std::collections::BTreeMap<NodeName, NodeConfig>),
}

impl NodeName {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_text()?))
    }

    pub fn to_nota(&self) -> String {
        NotaText::new(&self.0).format()
    }
}

impl NodeConfig {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_text()?))
    }

    pub fn to_nota(&self) -> String {
        NotaText::new(&self.0).format()
    }
}

impl Service {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        Ok(Self(NotaBlock::new(block).parse_text()?))
    }

    pub fn to_nota(&self) -> String {
        NotaText::new(&self.0).format()
    }
}

impl Cluster {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Cluster", 3)?;
        Ok(Self {
            nodes: NotaCollection::new(&children[0]).parse_map(NodeName::from_nota_block, NodeConfig::from_nota_block)?,
            services: NotaCollection::new(&children[1]).parse_vector(Service::from_nota_block)?,
            cache: NotaCollection::new(&children[2]).parse_option(Service::from_nota_block)?,
        })
    }

    pub fn to_nota(&self) -> String {
        let fields = [
            NotaCollection::format_map(&self.nodes, NodeName::to_nota, NodeConfig::to_nota),
            NotaCollection::format_vector(&self.services, Service::to_nota),
            NotaCollection::format_option(&self.cache, Service::to_nota),
        ];
        format!("({})", fields.join(" "))
    }
}

impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "Input", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Input", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Project" => Ok(Self::Project(Cluster::from_nota_block(&children[1])?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "Input", variant: other.to_owned() }),
        }
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Project(payload) => format!("(Project {})", payload.to_nota()),
        }
    }
}

impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        let root = NotaSource::new(source).parse_root()?;
        Self::from_nota_block(&root)
    }
}

impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.to_nota())
    }
}

impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        if let Some(variant) = block.demote_to_string() {
            return Err(NotaDecodeError::UnknownVariant { enum_name: "Output", variant: variant.to_owned() });
        }
        let children = NotaBlock::new(block).expect_children(nota_next::Delimiter::Parenthesis, "parenthesis", "Output", 2)?;
        let variant = children[0].demote_to_string().ok_or(NotaDecodeError::ExpectedAtom { type_name: "enum variant" })?;
        match variant {
            "Projected" => Ok(Self::Projected(NotaCollection::new(&children[1]).parse_map(NodeName::from_nota_block, NodeConfig::from_nota_block)?)),
            other => Err(NotaDecodeError::UnknownVariant { enum_name: "Output", variant: other.to_owned() }),
        }
    }

    pub fn to_nota(&self) -> String {
        match self {
            Self::Projected(payload) => format!("(Projected {})", NotaCollection::format_map(payload, NodeName::to_nota, NodeConfig::to_nota)),
        }
    }
}

impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        let root = NotaSource::new(source).parse_root()?;
        Self::from_nota_block(&root)
    }
}

impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.to_nota())
    }
}

pub mod short_header {
    pub const INPUT_PROJECT: u64 = 0x0000000000000000;
    pub const OUTPUT_PROJECTED: u64 = 0x0100000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InputRoute {
    Project,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OutputRoute {
    Projected,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Project(_) => InputRoute::Project,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Project(_) => short_header::INPUT_PROJECT,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_PROJECT => Ok(InputRoute::Project),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Projected(_) => OutputRoute::Projected,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Projected(_) => short_header::OUTPUT_PROJECTED,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_PROJECTED => Ok(OutputRoute::Projected),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct MessageIdentifier(pub Integer);

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct OriginRoute(pub Integer);

impl OriginRoute {
    pub fn at_ingress(value: Integer) -> Self {
        Self(value)
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum MessageRoot {
    Input,
    Output,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSent {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub root: MessageRoot,
    pub short_header: Integer,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NexusMail<Payload> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub payload: Payload,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageProcessed<Reply> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub reply: Reply,
}

pub trait MessageSentHook {
    type Error;

    fn message_sent(&mut self, event: MessageSent) -> Result<(), Self::Error>;
}

pub trait MessageProcessedHook<Reply> {
    type Error;

    fn message_processed(&mut self, event: MessageProcessed<Reply>) -> Result<(), Self::Error>;
}

impl MessageSent {
    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageSentHook,
    {
        hook.message_sent(self.clone())
    }
}

impl<Payload> NexusMail<Payload> {
    pub fn new(identifier: MessageIdentifier, origin_route: OriginRoute, payload: Payload) -> Self {
        Self { identifier, origin_route, payload }
    }

    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn into_payload(self) -> Payload {
        self.payload
    }
}

impl<Reply> MessageProcessed<Reply> {
    pub fn new(identifier: MessageIdentifier, origin_route: OriginRoute, reply: Reply) -> Self {
        Self { identifier, origin_route, reply }
    }

    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn into_reply(self) -> Reply {
        self.reply
    }

    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageProcessedHook<Reply>,
        Reply: Clone,
    {
        hook.message_processed(self.clone())
    }
}

impl Input {
    pub fn message_sent(&self, identifier: MessageIdentifier, origin_route: OriginRoute) -> MessageSent {
        MessageSent {
            identifier,
            origin_route,
            root: MessageRoot::Input,
            short_header: self.short_header(),
        }
    }
}

impl Output {
    pub fn message_sent(&self, identifier: MessageIdentifier, origin_route: OriginRoute) -> MessageSent {
        MessageSent {
            identifier,
            origin_route,
            root: MessageRoot::Output,
            short_header: self.short_header(),
        }
    }
}

pub trait InputNexus {
    type Reply;
    type Error;

    fn project(&self, mail: NexusMail<Cluster>) -> Result<Self::Reply, Self::Error>;
}

impl Input {
    pub fn dispatch_mail_with_nexus<Nexus>(self, identifier: MessageIdentifier, origin_route: OriginRoute, nexus: &Nexus) -> Result<MessageProcessed<Nexus::Reply>, Nexus::Error>
    where
        Nexus: InputNexus,
    {
        let reply = match self {
            Self::Project(payload) => nexus.project(NexusMail::new(identifier, origin_route, payload)),
        }?;
        Ok(MessageProcessed::new(identifier, origin_route, reply))
    }
}

pub trait OutputNexus {
    type Reply;
    type Error;

    fn projected(&self, mail: NexusMail<std::collections::BTreeMap<NodeName, NodeConfig>>) -> Result<Self::Reply, Self::Error>;
}

impl Output {
    pub fn dispatch_mail_with_nexus<Nexus>(self, identifier: MessageIdentifier, origin_route: OriginRoute, nexus: &Nexus) -> Result<MessageProcessed<Nexus::Reply>, Nexus::Error>
    where
        Nexus: OutputNexus,
    {
        let reply = match self {
            Self::Projected(payload) => nexus.projected(NexusMail::new(identifier, origin_route, payload)),
        }?;
        Ok(MessageProcessed::new(identifier, origin_route, reply))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Plane {
    Signal(OriginRoute, Input),
    Nexus(OriginRoute, Input),
    Sema(OriginRoute, Output),
}

impl Plane {
    pub fn at_ingress(origin_route: OriginRoute, request: Input) -> Self {
        Self::Signal(origin_route, request)
    }

    pub fn origin_route(&self) -> OriginRoute {
        match self {
            Self::Signal(origin_route, _) => *origin_route,
            Self::Nexus(origin_route, _) => *origin_route,
            Self::Sema(origin_route, _) => *origin_route,
        }
    }
}

pub trait SignalEngine {
    type Error;

    /// Validate the ingress request and admit it onto the Nexus
    /// plane, carrying the same origin route forward.
    fn admit(&self, signal: Plane) -> Result<Plane, Self::Error>;
}

pub trait NexusEngine {
    type Error;

    /// Execute the admitted request and hand the projected
    /// reply onto the Sema plane.
    fn execute(&self, nexus: Plane) -> Result<Plane, Self::Error>;
}

pub trait SemaEngine {
    type Error;

    /// Apply the reply to durable state and return the reply
    /// Plane to be echoed back to the caller.
    fn apply(&mut self, sema: Plane) -> Result<Plane, Self::Error>;
}

#[derive(Debug, PartialEq, Eq)]
pub enum PlaneChainError<SignalError, NexusError, SemaError> {
    Signal(SignalError),
    Nexus(NexusError),
    Sema(SemaError),
    UnexpectedPlane,
}

impl Plane {
    /// Drive the request through the three trait-ordered engines:
    /// Signal validates and pushes to Nexus, Nexus executes and
    /// pushes to Sema, Sema applies and returns the reply Plane.
    /// The origin route minted at ingress threads every hop and is
    /// echoed on the returned reply Plane.
    #[allow(clippy::type_complexity)]
    pub fn drive<Signal, Nexus, Sema>(
        self,
        signal: &Signal,
        nexus: &Nexus,
        sema: &mut Sema,
    ) -> Result<Plane, PlaneChainError<Signal::Error, Nexus::Error, Sema::Error>>
    where
        Signal: SignalEngine,
        Nexus: NexusEngine,
        Sema: SemaEngine,
    {
        let ingress_route = self.origin_route();
        let admitted = signal.admit(self).map_err(PlaneChainError::Signal)?;
        let Self::Nexus(_, _) = &admitted else {
            return Err(PlaneChainError::UnexpectedPlane);
        };
        let executed = nexus.execute(admitted).map_err(PlaneChainError::Nexus)?;
        let Self::Sema(_, _) = &executed else {
            return Err(PlaneChainError::UnexpectedPlane);
        };
        let reply = sema.apply(executed).map_err(PlaneChainError::Sema)?;
        debug_assert_eq!(reply.origin_route(), ingress_route);
        Ok(reply)
    }
}
pub trait UpgradeFrom<Previous>: Sized {
    type Error;

    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}

pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}

impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}
