// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use reaction::schema::reaction::Work as Work;
#[rustfmt::skip]
pub use reaction::schema::reaction::Action as Action;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalInput(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalOutput(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReadInput(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReadOutput(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaWriteOutput(Boolean);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Statement(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Removal(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LedgerEntry {
    pub statement: Statement,
    pub sequence: Integer,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EntryHandle(Statement);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteSet {
    Record(Record),
    Remove(Remove),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Record(LedgerEntry);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Remove(Removal);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectCommand {
    Append(Append),
    Prune(Prune),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Append(LedgerEntry);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Prune(Removal);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectOutcome {
    Appended(Appended),
    Pruned(Pruned),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Appended(EntryHandle);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Pruned(Removal);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SignalArrived(SignalInput),
    SemaWriteCompleted(SemaWriteOutput),
    SemaReadCompleted(SemaReadOutput),
    EffectCompleted(EffectOutcome),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ReplyToSignal(SignalOutput),
    CommandSemaWrite(SemaWriteSet),
    CommandSemaRead(SemaReadInput),
    CommandEffect(EffectCommand),
    Continue(Input),
}

#[rustfmt::skip]
impl SignalInput {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SignalInput {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SignalOutput {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SignalOutput {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SemaReadInput {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SemaReadOutput {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn new(payload: Boolean) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Boolean {
        &self.0
    }
    pub fn into_payload(self) -> Boolean {
        self.0
    }
}
#[rustfmt::skip]
impl From<Boolean> for SemaWriteOutput {
    fn from(payload: Boolean) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Statement {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Statement {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Removal {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Removal {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EntryHandle {
    pub fn new(payload: Statement) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Statement {
        &self.0
    }
    pub fn into_payload(self) -> Statement {
        self.0
    }
}
#[rustfmt::skip]
impl From<Statement> for EntryHandle {
    fn from(payload: Statement) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Record {
    pub fn new(payload: LedgerEntry) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LedgerEntry {
        &self.0
    }
    pub fn into_payload(self) -> LedgerEntry {
        self.0
    }
}
#[rustfmt::skip]
impl From<LedgerEntry> for Record {
    fn from(payload: LedgerEntry) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Remove {
    pub fn new(payload: Removal) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Removal {
        &self.0
    }
    pub fn into_payload(self) -> Removal {
        self.0
    }
}
#[rustfmt::skip]
impl From<Removal> for Remove {
    fn from(payload: Removal) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Append {
    pub fn new(payload: LedgerEntry) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LedgerEntry {
        &self.0
    }
    pub fn into_payload(self) -> LedgerEntry {
        self.0
    }
}
#[rustfmt::skip]
impl From<LedgerEntry> for Append {
    fn from(payload: LedgerEntry) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Prune {
    pub fn new(payload: Removal) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Removal {
        &self.0
    }
    pub fn into_payload(self) -> Removal {
        self.0
    }
}
#[rustfmt::skip]
impl From<Removal> for Prune {
    fn from(payload: Removal) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Appended {
    pub fn new(payload: EntryHandle) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EntryHandle {
        &self.0
    }
    pub fn into_payload(self) -> EntryHandle {
        self.0
    }
}
#[rustfmt::skip]
impl From<EntryHandle> for Appended {
    fn from(payload: EntryHandle) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Pruned {
    pub fn new(payload: Removal) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Removal {
        &self.0
    }
    pub fn into_payload(self) -> Removal {
        self.0
    }
}
#[rustfmt::skip]
impl From<Removal> for Pruned {
    fn from(payload: Removal) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LedgerEntry {
    pub fn new(statement: Statement, sequence: Integer) -> Self {
        Self { statement, sequence }
    }
    pub fn statement(&self) -> &Statement {
        &self.statement
    }
    pub fn sequence(&self) -> &Integer {
        &self.sequence
    }
}

#[rustfmt::skip]
impl SemaWriteSet {
    pub fn record(payload: LedgerEntry) -> Self {
        Self::Record(Record::new(payload))
    }
    pub fn remove(payload: Removal) -> Self {
        Self::Remove(Remove::new(payload))
    }
}

#[rustfmt::skip]
impl EffectCommand {
    pub fn append(payload: LedgerEntry) -> Self {
        Self::Append(Append::new(payload))
    }
    pub fn prune(payload: Removal) -> Self {
        Self::Prune(Prune::new(payload))
    }
}

#[rustfmt::skip]
impl EffectOutcome {
    pub fn appended(payload: EntryHandle) -> Self {
        Self::Appended(Appended::new(payload))
    }
    pub fn pruned(payload: Removal) -> Self {
        Self::Pruned(Pruned::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn signal_arrived(payload: String) -> Self {
        Self::SignalArrived(SignalInput::new(payload))
    }
    pub fn sema_write_completed(payload: Boolean) -> Self {
        Self::SemaWriteCompleted(SemaWriteOutput::new(payload))
    }
    pub fn sema_read_completed(payload: Integer) -> Self {
        Self::SemaReadCompleted(SemaReadOutput::new(payload))
    }
    pub fn effect_completed(payload: EffectOutcome) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn reply_to_signal(payload: String) -> Self {
        Self::ReplyToSignal(SignalOutput::new(payload))
    }
    pub fn command_sema_write(payload: SemaWriteSet) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn command_sema_read(payload: String) -> Self {
        Self::CommandSemaRead(SemaReadInput::new(payload))
    }
    pub fn command_effect(payload: EffectCommand) -> Self {
        Self::CommandEffect(payload)
    }
    pub fn r#continue(payload: Input) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl From<Record> for SemaWriteSet {
    fn from(payload: Record) -> Self {
        Self::Record(payload)
    }
}

#[rustfmt::skip]
impl From<Remove> for SemaWriteSet {
    fn from(payload: Remove) -> Self {
        Self::Remove(payload)
    }
}

#[rustfmt::skip]
impl From<Append> for EffectCommand {
    fn from(payload: Append) -> Self {
        Self::Append(payload)
    }
}

#[rustfmt::skip]
impl From<Prune> for EffectCommand {
    fn from(payload: Prune) -> Self {
        Self::Prune(payload)
    }
}

#[rustfmt::skip]
impl From<Appended> for EffectOutcome {
    fn from(payload: Appended) -> Self {
        Self::Appended(payload)
    }
}

#[rustfmt::skip]
impl From<Pruned> for EffectOutcome {
    fn from(payload: Pruned) -> Self {
        Self::Pruned(payload)
    }
}

#[rustfmt::skip]
impl From<SignalInput> for Input {
    fn from(payload: SignalInput) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteOutput> for Input {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadOutput> for Input {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<EffectOutcome> for Input {
    fn from(payload: EffectOutcome) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SignalOutput> for Output {
    fn from(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteSet> for Output {
    fn from(payload: SemaWriteSet) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadInput> for Output {
    fn from(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<EffectCommand> for Output {
    fn from(payload: EffectCommand) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<Input> for Output {
    fn from(payload: Input) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
impl Auditable for EntryHandle {}

#[rustfmt::skip]
impl std::ops::Deref for EntryHandle {
    type Target = Statement;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
