// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
    EffectCompleted(EffectCompleted),
}

#[rustfmt::skip]
pub type SignalArrived = Input;

#[rustfmt::skip]
pub type SemaWriteCompleted = SemaWriteOutput;

#[rustfmt::skip]
pub type SemaReadCompleted = SemaReadOutput;

#[rustfmt::skip]
pub type EffectCompleted = NexusEffectResult;

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    ReplyToSignal(ReplyToSignal),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

#[rustfmt::skip]
pub type CommandSemaWrite = SemaWriteInput;

#[rustfmt::skip]
pub type CommandSemaRead = SemaReadInput;

#[rustfmt::skip]
pub type ReplyToSignal = Output;

#[rustfmt::skip]
pub type CommandEffect = NexusEffectCommand;

#[rustfmt::skip]
pub type Continue = NexusWork;

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectCommand {
    Stash(StashRequest),
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectResult {
    Stashed(StashResult),
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteInput {
    Record(Entry),
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadInput {
    Observe(Query),
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteOutput {
    Recorded(SemaReceipt),
    Missed(ErrorReport),
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadOutput {
    Observed(ObservedRecords),
    Missed(ErrorReport),
}

#[rustfmt::skip]
pub type Topic = String;

#[rustfmt::skip]
pub type Description = String;

#[rustfmt::skip]
pub type ErrorMessage = String;

#[rustfmt::skip]
pub type RecordIdentifier = Integer;

#[rustfmt::skip]
pub type CommitSequence = Integer;

#[rustfmt::skip]
pub type StateDigest = Integer;

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DatabaseMarker {
    pub commit_sequence: CommitSequence,
    pub state_digest: StateDigest,
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReceipt {
    pub record_identifier: RecordIdentifier,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservedRecords {
    pub record_set: RecordSet,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
pub type StashHandle = Integer;

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StashResult {
    pub stash_handle: StashHandle,
    pub record_count: Integer,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StashRequest {
    pub record_set: RecordSet,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ErrorReport {
    pub error_message: ErrorMessage,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    pub topic: Topic,
    pub description: Description,
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query(pub Topic);

#[rustfmt::skip]
pub type RecordSet = Vec<Entry>;

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Record(Entry),
    Observe(Query),
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    RecordAccepted(SemaReceipt),
    RecordsStashed(StashResult),
    Error(ErrorReport),
}

#[rustfmt::skip]
impl Query {
    pub fn new(payload: Topic) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Topic {
        &self.0
    }
    pub fn into_payload(self) -> Topic {
        self.0
    }
}
#[rustfmt::skip]
impl From<Topic> for Query {
    fn from(payload: Topic) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NexusWork {
    pub fn signal_arrived(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
    pub fn sema_write_completed(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
    pub fn sema_read_completed(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
    pub fn effect_completed(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn command_sema_write(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn command_sema_read(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
    pub fn reply_to_signal(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
    pub fn command_effect(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
    pub fn r#continue(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl NexusEffectCommand {
    pub fn stash(payload: StashRequest) -> Self {
        Self::Stash(payload)
    }
}

#[rustfmt::skip]
impl NexusEffectResult {
    pub fn stashed(payload: StashResult) -> Self {
        Self::Stashed(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn record(payload: Entry) -> Self {
        Self::Record(payload)
    }
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn observe(payload: Topic) -> Self {
        Self::Observe(Query::new(payload))
    }
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn recorded(payload: SemaReceipt) -> Self {
        Self::Recorded(payload)
    }
    pub fn missed(payload: ErrorReport) -> Self {
        Self::Missed(payload)
    }
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn observed(payload: ObservedRecords) -> Self {
        Self::Observed(payload)
    }
    pub fn missed(payload: ErrorReport) -> Self {
        Self::Missed(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn record(payload: Entry) -> Self {
        Self::Record(payload)
    }
    pub fn observe(payload: Topic) -> Self {
        Self::Observe(Query::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn record_accepted(payload: SemaReceipt) -> Self {
        Self::RecordAccepted(payload)
    }
    pub fn records_stashed(payload: StashResult) -> Self {
        Self::RecordsStashed(payload)
    }
    pub fn error(payload: ErrorReport) -> Self {
        Self::Error(payload)
    }
}

#[rustfmt::skip]
impl From<StashRequest> for NexusEffectCommand {
    fn from(payload: StashRequest) -> Self {
        Self::Stash(payload)
    }
}

#[rustfmt::skip]
impl From<StashResult> for NexusEffectResult {
    fn from(payload: StashResult) -> Self {
        Self::Stashed(payload)
    }
}

#[rustfmt::skip]
impl From<Entry> for SemaWriteInput {
    fn from(payload: Entry) -> Self {
        Self::Record(payload)
    }
}

#[rustfmt::skip]
impl From<Query> for SemaReadInput {
    fn from(payload: Query) -> Self {
        Self::Observe(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReceipt> for SemaWriteOutput {
    fn from(payload: SemaReceipt) -> Self {
        Self::Recorded(payload)
    }
}

#[rustfmt::skip]
impl From<ErrorReport> for SemaWriteOutput {
    fn from(payload: ErrorReport) -> Self {
        Self::Missed(payload)
    }
}

#[rustfmt::skip]
impl From<ObservedRecords> for SemaReadOutput {
    fn from(payload: ObservedRecords) -> Self {
        Self::Observed(payload)
    }
}

#[rustfmt::skip]
impl From<ErrorReport> for SemaReadOutput {
    fn from(payload: ErrorReport) -> Self {
        Self::Missed(payload)
    }
}

#[rustfmt::skip]
impl From<Entry> for Input {
    fn from(payload: Entry) -> Self {
        Self::Record(payload)
    }
}

#[rustfmt::skip]
impl From<Query> for Input {
    fn from(payload: Query) -> Self {
        Self::Observe(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReceipt> for Output {
    fn from(payload: SemaReceipt) -> Self {
        Self::RecordAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<StashResult> for Output {
    fn from(payload: StashResult) -> Self {
        Self::RecordsStashed(payload)
    }
}

#[rustfmt::skip]
impl From<ErrorReport> for Output {
    fn from(payload: ErrorReport) -> Self {
        Self::Error(payload)
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_RECORD: u64 = 0x0000000000000000;
    pub const INPUT_OBSERVE: u64 = 0x0001000000000000;
    pub const OUTPUT_RECORD_ACCEPTED: u64 = 0x0100000000000000;
    pub const OUTPUT_RECORDS_STASHED: u64 = 0x0101000000000000;
    pub const OUTPUT_ERROR: u64 = 0x0102000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Record,
    Observe,
}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    RecordAccepted,
    RecordsStashed,
    Error,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Record(_) => InputRoute::Record,
            Self::Observe(_) => InputRoute::Observe,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Record(_) => short_header::INPUT_RECORD,
            Self::Observe(_) => short_header::INPUT_OBSERVE,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_RECORD => Ok(InputRoute::Record),
            short_header::INPUT_OBSERVE => Ok(InputRoute::Observe),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::RecordAccepted(_) => OutputRoute::RecordAccepted,
            Self::RecordsStashed(_) => OutputRoute::RecordsStashed,
            Self::Error(_) => OutputRoute::Error,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::RecordAccepted(_) => short_header::OUTPUT_RECORD_ACCEPTED,
            Self::RecordsStashed(_) => short_header::OUTPUT_RECORDS_STASHED,
            Self::Error(_) => short_header::OUTPUT_ERROR,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_RECORD_ACCEPTED => Ok(OutputRoute::RecordAccepted),
            short_header::OUTPUT_RECORDS_STASHED => Ok(OutputRoute::RecordsStashed),
            short_header::OUTPUT_ERROR => Ok(OutputRoute::Error),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusWorkRoute {
    SignalArrived,
    SemaWriteCompleted,
    SemaReadCompleted,
    EffectCompleted,
}

#[rustfmt::skip]
impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusActionRoute {
    CommandSemaWrite,
    CommandSemaRead,
    ReplyToSignal,
    CommandEffect,
    Continue,
}

#[rustfmt::skip]
impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaWriteInputRoute {
    Record,
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn route(&self) -> SemaWriteInputRoute {
        match self {
            Self::Record(_) => SemaWriteInputRoute::Record,
        }
    }
}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaReadInputRoute {
    Observe,
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn route(&self) -> SemaReadInputRoute {
        match self {
            Self::Observe(_) => SemaReadInputRoute::Observe,
        }
    }
}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaWriteOutputRoute {
    Recorded,
    Missed,
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn route(&self) -> SemaWriteOutputRoute {
        match self {
            Self::Recorded(_) => SemaWriteOutputRoute::Recorded,
            Self::Missed(_) => SemaWriteOutputRoute::Missed,
        }
    }
}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaReadOutputRoute {
    Observed,
    Missed,
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn route(&self) -> SemaReadOutputRoute {
        match self {
            Self::Observed(_) => SemaReadOutputRoute::Observed,
            Self::Missed(_) => SemaReadOutputRoute::Missed,
        }
    }
}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SignalObjectName {
    Input(InputRoute),
    Output(OutputRoute),
    Started,
    Stopped,
    Admitted,
    Rejected,
    Triaged,
    Replied,
}
#[rustfmt::skip]
impl SignalObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Input(route) => {
                match route {
                    InputRoute::Record => "SignalInputRecord",
                    InputRoute::Observe => "SignalInputObserve",
                }
            }
            Self::Output(route) => {
                match route {
                    OutputRoute::RecordAccepted => "SignalOutputRecordAccepted",
                    OutputRoute::RecordsStashed => "SignalOutputRecordsStashed",
                    OutputRoute::Error => "SignalOutputError",
                }
            }
            Self::Started => "SignalStarted",
            Self::Stopped => "SignalStopped",
            Self::Admitted => "SignalAdmitted",
            Self::Rejected => "SignalRejected",
            Self::Triaged => "SignalTriaged",
            Self::Replied => "SignalReplied",
        }
    }
}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}
#[rustfmt::skip]
impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => {
                match route {
                    NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                    NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                    NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                    NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
                }
            }
            Self::Action(route) => {
                match route {
                    NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                    NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                    NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                    NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                    NexusActionRoute::Continue => "NexusActionContinue",
                }
            }
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaObjectName {
    WriteInput(SemaWriteInputRoute),
    ReadInput(SemaReadInputRoute),
    WriteOutput(SemaWriteOutputRoute),
    ReadOutput(SemaReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}
#[rustfmt::skip]
impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => {
                match route {
                    SemaWriteInputRoute::Record => "SemaWriteInputRecord",
                }
            }
            Self::ReadInput(route) => {
                match route {
                    SemaReadInputRoute::Observe => "SemaReadInputObserve",
                }
            }
            Self::WriteOutput(route) => {
                match route {
                    SemaWriteOutputRoute::Recorded => "SemaWriteOutputRecorded",
                    SemaWriteOutputRoute::Missed => "SemaWriteOutputMissed",
                }
            }
            Self::ReadOutput(route) => {
                match route {
                    SemaReadOutputRoute::Observed => "SemaReadOutputObserved",
                    SemaReadOutputRoute::Missed => "SemaReadOutputMissed",
                }
            }
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Signal(SignalObjectName),
    Nexus(NexusObjectName),
    Sema(SemaObjectName),
}
#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Signal(object_name) => object_name.name(),
            Self::Nexus(object_name) => object_name.name(),
            Self::Sema(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct MessageIdentifier(pub Integer);

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(pub Integer);

#[rustfmt::skip]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MessageRoot {
    Input,
    Output,
}

#[rustfmt::skip]
pub mod schema {
    #[derive(
        rkyv::Archive,
        rkyv::Serialize,
        rkyv::Deserialize,
        Clone,
        Debug,
        PartialEq,
        Eq
    )]
    pub enum Plane<SignalRoot, NexusRoot, SemaRoot> {
        Signal(super::Signal<SignalRoot>),
        Nexus(super::Nexus<NexusRoot>),
        Sema(super::Sema<SemaRoot>),
    }
    impl<SignalRoot, NexusRoot, SemaRoot> Plane<SignalRoot, NexusRoot, SemaRoot> {
        pub fn origin_route(&self) -> super::OriginRoute {
            match self {
                Self::Signal(message) => message.origin_route(),
                Self::Nexus(message) => message.origin_route(),
                Self::Sema(message) => message.origin_route(),
            }
        }
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Signal<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Signal<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Signal<NextRoot> {
        Signal::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSent {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub root: MessageRoot,
    pub short_header: Integer,
}
#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageProcessed<Reply> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub reply: Reply,
}
#[rustfmt::skip]
pub trait MessageSentHook {
    type Error;
    fn message_sent(&mut self, event: MessageSent) -> Result<(), Self::Error>;
}
#[rustfmt::skip]
pub trait MessageProcessedHook<Reply> {
    type Error;
    fn message_processed(
        &mut self,
        event: MessageProcessed<Reply>,
    ) -> Result<(), Self::Error>;
}
#[rustfmt::skip]
impl MessageSent {
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageSentHook,
    {
        hook.message_sent(self.clone())
    }
}
#[rustfmt::skip]
impl<Reply> MessageProcessed<Reply> {
    pub fn new(
        identifier: MessageIdentifier,
        origin_route: OriginRoute,
        reply: Reply,
    ) -> Self {
        Self {
            identifier,
            origin_route,
            reply,
        }
    }
    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn into_reply(self) -> Reply {
        self.reply
    }
    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageProcessedHook<Reply>,
        Reply: Clone,
    {
        hook.message_processed(self.clone())
    }
}
#[rustfmt::skip]
impl Input {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }
}
#[rustfmt::skip]
impl signal::Signal<Input> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Input,
            short_header: self.root().short_header(),
        }
    }
}
#[rustfmt::skip]
impl Output {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }
}
#[rustfmt::skip]
impl signal::Signal<Output> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Output,
            short_header: self.root().short_header(),
        }
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod signal {
    pub type Input = super::Input;
    pub type Output = super::Output;
    pub type Signal<Root> = super::Signal<Root>;
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::SemaWriteInput;
    pub type WriteOutput = super::SemaWriteOutput;
    pub type ReadInput = super::SemaReadInput;
    pub type ReadOutput = super::SemaReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

#[rustfmt::skip]
impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaWriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaWriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl SemaReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::NexusWork for NexusWork {}

#[rustfmt::skip]
impl triad_runtime::SemaWriteInput for CommandSemaWrite {}

#[rustfmt::skip]
impl triad_runtime::SemaReadInput for CommandSemaRead {}

#[rustfmt::skip]
impl triad_runtime::NexusEffectCommand for CommandEffect {}

#[rustfmt::skip]
impl triad_runtime::NexusEffectResult for EffectCompleted {}

#[rustfmt::skip]
impl triad_runtime::SemaWriteOutput for SemaWriteOutput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadOutput for SemaReadOutput {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for ActorStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "actor resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "actor configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for ActorStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for ActorStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "actor resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "actor child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for ActorStopFailure {}

#[rustfmt::skip]
pub type NexusRunnerNextStep = triad_runtime::NextStep<
    ReplyToSignal,
    CommandSemaWrite,
    CommandSemaRead,
    CommandEffect,
    NexusWork,
>;
#[rustfmt::skip]
impl triad_runtime::NexusAction for NexusAction {
    type Reply = ReplyToSignal;
    type SemaWrite = CommandSemaWrite;
    type SemaRead = CommandSemaRead;
    type Effect = CommandEffect;
    type Work = NexusWork;
    fn into_next_step(self) -> NexusRunnerNextStep {
        match self {
            Self::CommandSemaWrite(input) => triad_runtime::NextStep::SemaWrite(input),
            Self::CommandSemaRead(input) => triad_runtime::NextStep::SemaRead(input),
            Self::ReplyToSignal(output) => triad_runtime::NextStep::Reply(output),
            Self::CommandEffect(effect) => triad_runtime::NextStep::RunEffect(effect),
            Self::Continue(work) => triad_runtime::NextStep::Continue(work),
        }
    }
}

#[rustfmt::skip]
pub trait SignalEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }
    fn trace_signal_activation(&self, _object_name: SignalObjectName) {}
    fn trace_signal_admitted(&self) {
        self.trace_signal_activation(SignalObjectName::Admitted);
    }
    fn trace_signal_rejected(&self) {
        self.trace_signal_activation(SignalObjectName::Rejected);
    }
    fn trace_signal_triaged(&self) {
        self.trace_signal_activation(SignalObjectName::Triaged);
    }
    fn trace_signal_replied(&self) {
        self.trace_signal_activation(SignalObjectName::Replied);
    }
    fn triage_inner(
        &self,
        input: signal::Signal<signal::Input>,
    ) -> nexus::Nexus<nexus::Work>;
    fn reply_inner(
        &self,
        output: nexus::Nexus<nexus::Action>,
    ) -> signal::Signal<signal::Output>;
    fn triage(&self, input: signal::Signal<signal::Input>) -> nexus::Nexus<nexus::Work> {
        let output = self.triage_inner(input);
        self.trace_signal_triaged();
        output
    }
    fn reply(
        &self,
        output: nexus::Nexus<nexus::Action>,
    ) -> signal::Signal<signal::Output> {
        let signal_output = self.reply_inner(output);
        self.trace_signal_replied();
        signal_output
    }
}

#[rustfmt::skip]
pub trait NexusEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }
    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }
    fn continuation_limit(&self) -> triad_runtime::ContinuationLimit {
        triad_runtime::ContinuationLimit::default()
    }
    fn apply_sema_write(
        &mut self,
        origin_route: OriginRoute,
        input: CommandSemaWrite,
    ) -> SemaWriteCompleted;
    fn observe_sema_read(
        &self,
        origin_route: OriginRoute,
        input: CommandSemaRead,
    ) -> SemaReadCompleted;
    fn run_effect(&mut self, input: CommandEffect) -> EffectCompleted;
    fn budget_exhausted_reply(
        &self,
        exhausted: triad_runtime::ContinuationExhausted,
    ) -> ReplyToSignal;
    fn decide(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>;
    fn execute(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>
    where
        Self: Sized,
    {
        self.trace_nexus_entered();
        let origin_route = input.origin_route();
        let first_work = input.into_root();
        let runner = triad_runtime::Runner::new(self.continuation_limit());
        let mut runner_adapter = NexusRunnerAdapter::new(self, origin_route);
        let reply = runner.drive(&mut runner_adapter, first_work);
        let output = NexusAction::reply_to_signal(reply).with_origin_route(origin_route);
        self.trace_nexus_decided();
        output
    }
}

#[rustfmt::skip]
struct NexusRunnerAdapter<'engine, Engine> {
    engine: &'engine mut Engine,
    origin_route: OriginRoute,
}
#[rustfmt::skip]
impl<'engine, Engine> NexusRunnerAdapter<'engine, Engine> {
    fn new(engine: &'engine mut Engine, origin_route: OriginRoute) -> Self {
        Self { engine, origin_route }
    }
}
#[rustfmt::skip]
impl<'engine, Engine> triad_runtime::RunnerEngines
for NexusRunnerAdapter<'engine, Engine>
where
    Engine: NexusEngine,
{
    type Reply = ReplyToSignal;
    type SemaWrite = CommandSemaWrite;
    type SemaRead = CommandSemaRead;
    type Effect = CommandEffect;
    type Work = NexusWork;
    fn decide_next_step(
        &mut self,
        work: Self::Work,
    ) -> triad_runtime::runner::RunnerNextStep<Self> {
        let action = NexusEngine::decide(
                self.engine,
                work.with_origin_route(self.origin_route),
            )
            .into_root();
        triad_runtime::NexusAction::into_next_step(action)
    }
    fn apply_sema_write(&mut self, write: Self::SemaWrite) -> Self::Work {
        let output: SemaWriteCompleted = NexusEngine::apply_sema_write(
            self.engine,
            self.origin_route,
            write,
        );
        NexusWork::sema_write_completed(output)
    }
    fn observe_sema_read(&self, read: Self::SemaRead) -> Self::Work {
        let output: SemaReadCompleted = NexusEngine::observe_sema_read(
            self.engine,
            self.origin_route,
            read,
        );
        NexusWork::sema_read_completed(output)
    }
    fn run_effect(&mut self, effect: Self::Effect) -> Self::Work {
        let output: EffectCompleted = NexusEngine::run_effect(self.engine, effect);
        NexusWork::effect_completed(output)
    }
    fn budget_exhausted_reply(
        &self,
        exhausted: triad_runtime::ContinuationExhausted,
    ) -> Self::Reply {
        NexusEngine::budget_exhausted_reply(self.engine, exhausted)
    }
}

#[rustfmt::skip]
pub trait SemaEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }
    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }
    fn apply_inner(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput>;
    fn apply(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }
    fn observe(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
