use schema_next::{
    Asschema, EnumDeclaration, EnumVariant, Name, ResolvedImport, StructDeclaration,
    TypeDeclaration, TypeReference,
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedFile {
    pub path: String,
    pub code: RustCode,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RustCode(String);

impl RustCode {
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

#[derive(Clone, Debug)]
pub struct RustEmitter {
    generator_name: &'static str,
}

impl Default for RustEmitter {
    fn default() -> Self {
        Self {
            generator_name: "schema-rust-next",
        }
    }
}

impl RustEmitter {
    pub fn emit_file(&self, asschema: &Asschema) -> GeneratedFile {
        GeneratedFile {
            path: RustModulePath::new(asschema.identity().component().clone()).to_file_path(),
            code: self.emit(asschema),
        }
    }

    pub fn emit(&self, asschema: &Asschema) -> RustCode {
        let mut writer = RustWriter::default();
        let roots = asschema
            .roots()
            .iter()
            .map(|root| root.enum_declaration())
            .collect::<Vec<_>>();
        writer.note_map_key_types(CollectionScan::new(asschema).map_key_type_names());
        writer.line(format!("// @generated by {}", self.generator_name));
        writer.blank();
        writer.line("pub type String = std::string::String;");
        writer.line("pub type Integer = u64;");
        writer.line("pub type Boolean = bool;");
        writer.line("pub type Path = std::string::String;");
        writer.blank();
        writer.emit_imports(asschema.resolved_imports());
        writer.emit_nota_support();
        writer.blank();

        for declaration in asschema.namespace() {
            writer.emit_type(declaration);
            writer.blank();
        }

        for root_enum in &roots {
            writer.emit_root_enum(root_enum);
            writer.blank();
        }

        writer.emit_nota_type_bridges(asschema.namespace());
        for root_enum in &roots {
            writer.emit_nota_root_enum_support(root_enum);
            writer.blank();
        }

        writer.emit_short_headers(&roots);
        writer.blank();
        writer.emit_signal_frame_support(&roots);
        writer.emit_mail_event_support(&roots);
        writer.emit_plane_namespaces(asschema.namespace(), &roots);
        writer.emit_nexus_support(&roots);
        writer.emit_schema_plane_trait_support(asschema.namespace());
        writer.emit_upgrade_support();
        RustCode(writer.finish())
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct RustModulePath {
    schema_name: Name,
}

impl RustModulePath {
    fn new(schema_name: Name) -> Self {
        Self { schema_name }
    }

    fn to_file_path(&self) -> String {
        let mut segments = self.module_segments();
        let file = segments.pop().unwrap_or_else(|| "lib".to_owned());
        if segments.is_empty() {
            format!("src/schema/{file}.rs")
        } else {
            format!("src/schema/{}/{}.rs", segments.join("/"), file)
        }
    }

    fn module_segments(&self) -> Vec<String> {
        let segments = self.schema_name.namespace_segments();
        let module_segments = if segments.len() > 1 {
            &segments[1..]
        } else {
            segments.as_slice()
        };
        module_segments
            .iter()
            .map(|segment| Name::new(*segment).field_name())
            .collect()
    }
}

/// Decides which assembled schema type names appear as map keys.
#[derive(Clone, Copy, Debug)]
struct CollectionScan<'asschema> {
    asschema: &'asschema Asschema,
}

impl<'asschema> CollectionScan<'asschema> {
    fn new(asschema: &'asschema Asschema) -> Self {
        Self { asschema }
    }

    /// The plain type names that appear as a `BTreeMap` key anywhere in
    /// the schema (field references, variant payloads, and nested
    /// collection positions). These types need the ordering derives.
    fn map_key_type_names(&self) -> Vec<String> {
        let mut names = Vec::new();
        for declaration in self.asschema.namespace() {
            match declaration {
                TypeDeclaration::Struct(declaration) | TypeDeclaration::Newtype(declaration) => {
                    for field in &declaration.fields {
                        Self::collect_map_keys(&field.reference, &mut names);
                    }
                }
                TypeDeclaration::Enum(declaration) => {
                    Self::collect_enum_map_keys(declaration, &mut names);
                }
            }
        }
        for root in self.asschema.roots() {
            Self::collect_enum_map_keys(root.enum_declaration(), &mut names);
        }
        names
    }

    fn collect_enum_map_keys(declaration: &EnumDeclaration, names: &mut Vec<String>) {
        for variant in &declaration.variants {
            if let Some(payload) = &variant.payload {
                Self::collect_map_keys(payload, names);
            }
        }
    }

    fn collect_map_keys(reference: &TypeReference, names: &mut Vec<String>) {
        match reference {
            TypeReference::String
            | TypeReference::Integer
            | TypeReference::Boolean
            | TypeReference::Path
            | TypeReference::Plain(_) => {}
            TypeReference::Vector(inner) | TypeReference::Optional(inner) => {
                Self::collect_map_keys(inner, names);
            }
            TypeReference::Map(key, value) => {
                if let TypeReference::Plain(name) = key.as_ref() {
                    let name = name.as_str().to_owned();
                    if !names.contains(&name) {
                        names.push(name);
                    }
                }
                Self::collect_map_keys(key, names);
                Self::collect_map_keys(value, names);
            }
        }
    }
}

#[derive(Default)]
struct RustWriter {
    output: String,
    map_key_types: Vec<String>,
}

impl RustWriter {
    /// Record the set of type names used as a `BTreeMap` key anywhere
    /// in the schema. A map key type additionally derives `PartialOrd,
    /// Ord` (and the archived form does too) so `BTreeMap<Key, _>`
    /// compiles. Non-key types keep the original derive set, so a
    /// collection-free schema's emission stays byte-identical.
    fn note_map_key_types(&mut self, key_types: Vec<String>) {
        self.map_key_types = key_types;
    }

    /// The derive attribute line for a data-bearing emitted type. Adds
    /// the ordering derives when the type is used as a map key.
    fn data_type_derive(&self, type_name: &Name) -> String {
        if self
            .map_key_types
            .iter()
            .any(|key| key == type_name.as_str())
        {
            "#[derive(nota_next::NotaDecode, nota_next::NotaEncode, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]\n#[rkyv(derive(PartialEq, Eq, PartialOrd, Ord))]".to_owned()
        } else {
            "#[derive(nota_next::NotaDecode, nota_next::NotaEncode, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]".to_owned()
        }
    }

    fn line(&mut self, line: impl AsRef<str>) {
        self.output.push_str(line.as_ref());
        self.output.push('\n');
    }

    fn blank(&mut self) {
        self.output.push('\n');
    }

    fn finish(self) -> String {
        self.output
    }

    /// Emit a `pub use` alias for each cross-crate import.
    ///
    /// The dependency crate emits its own definition of the type; the
    /// consumer references that type through the local alias instead of
    /// re-declaring it. Later fields or variants that name the imported
    /// type therefore use the dependency crate's type identity.
    fn emit_imports(&mut self, imports: &[ResolvedImport]) {
        if imports.is_empty() {
            return;
        }
        for import in imports {
            self.line(import.use_item());
        }
        self.blank();
    }

    fn emit_type(&mut self, declaration: &TypeDeclaration) {
        match declaration {
            TypeDeclaration::Struct(declaration) => self.emit_struct(declaration),
            TypeDeclaration::Newtype(declaration) => self.emit_newtype(declaration),
            TypeDeclaration::Enum(declaration) => self.emit_enum(declaration),
        }
    }

    fn emit_nota_support(&mut self) {
        self.line("pub use nota_next::{");
        self.line("    NotaDecode, NotaDecodeError, NotaEncode, NotaSource,");
        self.line("};");
    }

    fn emit_newtype(&mut self, declaration: &StructDeclaration) {
        let field = declaration.fields.first().expect("newtype has one field");
        let derive = self.data_type_derive(&declaration.name);
        self.line(derive);
        self.line(format!(
            "pub struct {}(pub {});",
            declaration.name,
            self.rust_type(&field.reference)
        ));
    }

    fn emit_struct(&mut self, declaration: &StructDeclaration) {
        let derive = self.data_type_derive(&declaration.name);
        self.line(derive);
        self.line(format!("pub struct {} {{", declaration.name));
        for field in &declaration.fields {
            self.line(format!(
                "    pub {}: {},",
                field.name.as_str(),
                self.rust_type(&field.reference)
            ));
        }
        self.line("}");
    }

    fn emit_enum(&mut self, declaration: &EnumDeclaration) {
        let derive = self.data_type_derive(&declaration.name);
        self.line(derive);
        self.line(format!("pub enum {} {{", declaration.name));
        for variant in &declaration.variants {
            self.emit_variant(variant);
        }
        self.line("}");
    }

    fn emit_root_enum(&mut self, root_enum: &EnumDeclaration) {
        self.line("#[derive(nota_next::NotaDecode, nota_next::NotaEncode, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]");
        self.line(format!("pub enum {} {{", root_enum.name));
        for variant in &root_enum.variants {
            self.emit_variant(variant);
        }
        self.line("}");
    }

    fn emit_variant(&mut self, variant: &EnumVariant) {
        match &variant.payload {
            Some(reference) => self.line(format!(
                "    {}({}),",
                variant.name,
                self.rust_type(reference)
            )),
            None => self.line(format!("    {},", variant.name)),
        }
    }

    fn emit_nota_type_bridges(&mut self, declarations: &[TypeDeclaration]) {
        for declaration in declarations {
            self.emit_nota_inherent_bridge(declaration.name().as_str());
            self.blank();
        }
    }

    fn emit_nota_inherent_bridge(&mut self, name: &str) {
        self.line(format!("impl {name} {{"));
        self.line("    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {");
        self.line("        <Self as NotaDecode>::from_nota_block(block)");
        self.line("    }");
        self.blank();
        self.line("    pub fn to_nota(&self) -> String {");
        self.line("        <Self as NotaEncode>::to_nota(self)");
        self.line("    }");
        self.line("}");
    }

    fn emit_nota_copy_inherent_bridge(&mut self, name: &str) {
        self.line(format!("impl {name} {{"));
        self.line("    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {");
        self.line("        <Self as NotaDecode>::from_nota_block(block)");
        self.line("    }");
        self.blank();
        self.line("    pub fn to_nota(self) -> String {");
        self.line("        <Self as NotaEncode>::to_nota(&self)");
        self.line("    }");
        self.line("}");
    }

    fn emit_nota_root_enum_support(&mut self, root_enum: &EnumDeclaration) {
        self.emit_nota_inherent_bridge(root_enum.name.as_str());
        self.blank();
        self.line(format!("impl std::str::FromStr for {} {{", root_enum.name));
        self.line("    type Err = NotaDecodeError;");
        self.blank();
        self.line("    fn from_str(source: &str) -> Result<Self, Self::Err> {");
        self.line("        NotaSource::new(source).parse::<Self>()");
        self.line("    }");
        self.line("}");
        self.blank();
        self.line(format!("impl std::fmt::Display for {} {{", root_enum.name));
        self.line(
            "    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {",
        );
        self.line("        formatter.write_str(&<Self as NotaEncode>::to_nota(self))");
        self.line("    }");
        self.line("}");
    }

    fn emit_short_headers(&mut self, root_enums: &[&EnumDeclaration]) {
        self.line("pub mod short_header {");
        for (root_index, root_enum) in root_enums.iter().enumerate() {
            for (variant_index, variant) in root_enum.variants.iter().enumerate() {
                let constant = format!(
                    "{}_{}",
                    self.constant_name(&root_enum.name),
                    self.constant_name(&variant.name)
                );
                let value = ((root_index as u64) << 56) | ((variant_index as u64) << 48);
                self.line(format!("    pub const {constant}: u64 = 0x{value:016X};"));
            }
        }
        self.line("}");
    }

    fn emit_signal_frame_support(&mut self, root_enums: &[&EnumDeclaration]) {
        self.line("const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;");
        self.blank();
        self.line("#[derive(Clone, Debug, PartialEq, Eq)]");
        self.line("pub enum SignalFrameError {");
        self.line("    ArchiveEncode,");
        self.line("    ArchiveDecode,");
        self.line("    FrameTooShort { found: usize },");
        self.line("    UnknownHeader { root_enum: &'static str, header: u64 },");
        self.line("    HeaderMismatch { expected: u64, found: u64 },");
        self.line("}");
        self.blank();
        self.line("impl std::fmt::Display for SignalFrameError {");
        self.line(
            "    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {",
        );
        self.line("        match self {");
        self.line("            Self::ArchiveEncode => formatter.write_str(\"failed to encode rkyv archive\"),");
        self.line("            Self::ArchiveDecode => formatter.write_str(\"failed to decode rkyv archive\"),");
        self.line("            Self::FrameTooShort { found } => write!(formatter, \"signal frame too short: {found} bytes\"),");
        self.line("            Self::UnknownHeader { root_enum, header } => write!(formatter, \"unknown {root_enum} short header 0x{header:016X}\"),");
        self.line("            Self::HeaderMismatch { expected, found } => write!(formatter, \"decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}\"),");
        self.line("        }");
        self.line("    }");
        self.line("}");
        self.blank();
        self.line("impl std::error::Error for SignalFrameError {}");
        self.blank();

        for root_enum in root_enums {
            self.emit_route_enum(root_enum);
            self.blank();
        }

        for root_enum in root_enums {
            self.emit_signal_frame_impl(root_enum);
            self.blank();
        }
    }

    fn emit_route_enum(&mut self, root_enum: &EnumDeclaration) {
        self.line("#[derive(Clone, Copy, Debug, Eq, PartialEq)]");
        self.line(format!("pub enum {}Route {{", root_enum.name));
        for variant in &root_enum.variants {
            self.line(format!("    {},", variant.name));
        }
        self.line("}");
    }

    fn emit_signal_frame_impl(&mut self, root_enum: &EnumDeclaration) {
        let route_name = format!("{}Route", root_enum.name);
        self.line(format!("impl {} {{", root_enum.name));
        self.line(format!("    pub fn route(&self) -> {route_name} {{"));
        self.line("        match self {");
        for variant in &root_enum.variants {
            match &variant.payload {
                Some(_) => self.line(format!(
                    "            Self::{}(_) => {route_name}::{},",
                    variant.name, variant.name
                )),
                None => self.line(format!(
                    "            Self::{} => {route_name}::{},",
                    variant.name, variant.name
                )),
            }
        }
        self.line("        }");
        self.line("    }");
        self.blank();
        self.line("    pub fn short_header(&self) -> u64 {");
        self.line("        match self {");
        for variant in &root_enum.variants {
            let constant = format!(
                "{}_{}",
                self.constant_name(&root_enum.name),
                self.constant_name(&variant.name)
            );
            match &variant.payload {
                Some(_) => self.line(format!(
                    "            Self::{}(_) => short_header::{constant},",
                    variant.name
                )),
                None => self.line(format!(
                    "            Self::{} => short_header::{constant},",
                    variant.name
                )),
            }
        }
        self.line("        }");
        self.line("    }");
        self.blank();
        self.line(format!(
            "    pub fn route_from_short_header(header: u64) -> Result<{route_name}, SignalFrameError> {{"
        ));
        self.line("        match header {");
        for variant in &root_enum.variants {
            let constant = format!(
                "{}_{}",
                self.constant_name(&root_enum.name),
                self.constant_name(&variant.name)
            );
            self.line(format!(
                "            short_header::{constant} => Ok({route_name}::{}),",
                variant.name
            ));
        }
        self.line(format!(
            "            _ => Err(SignalFrameError::UnknownHeader {{ root_enum: \"{}\", header }}),",
            root_enum.name
        ));
        self.line("        }");
        self.line("    }");
        self.blank();
        self.line("    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {");
        self.line("        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)");
        self.line("            .map_err(|_| SignalFrameError::ArchiveEncode)?;");
        self.line("        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());");
        self.line("        frame.extend_from_slice(&self.short_header().to_le_bytes());");
        self.line("        frame.extend_from_slice(&archive);");
        self.line("        Ok(frame)");
        self.line("    }");
        self.blank();
        self.line(format!(
            "    pub fn decode_signal_frame(frame: &[u8]) -> Result<({route_name}, Self), SignalFrameError> {{"
        ));
        self.line("        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {");
        self.line(
            "            return Err(SignalFrameError::FrameTooShort { found: frame.len() });",
        );
        self.line("        }");
        self.line("        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];");
        self.line(
            "        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);",
        );
        self.line("        let header = u64::from_le_bytes(header_bytes);");
        self.line("        let route = Self::route_from_short_header(header)?;");
        self.line("        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])");
        self.line("            .map_err(|_| SignalFrameError::ArchiveDecode)?;");
        self.line("        let expected = value.short_header();");
        self.line("        if expected != header {");
        self.line(
            "            return Err(SignalFrameError::HeaderMismatch { expected, found: header });",
        );
        self.line("        }");
        self.line("        Ok((route, value))");
        self.line("    }");
        self.line("}");
    }

    fn emit_mail_event_support(&mut self, root_enums: &[&EnumDeclaration]) {
        self.line("#[derive(nota_next::NotaDecode, nota_next::NotaEncode, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]");
        self.line("pub struct MessageIdentifier(pub Integer);");
        self.emit_nota_copy_inherent_bridge("MessageIdentifier");
        self.blank();
        self.line("#[derive(nota_next::NotaDecode, nota_next::NotaEncode, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]");
        self.line("pub struct OriginRoute(pub Integer);");
        self.emit_nota_copy_inherent_bridge("OriginRoute");
        self.blank();
        self.line("#[derive(nota_next::NotaDecode, nota_next::NotaEncode, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]");
        self.line("pub enum MessageRoot {");
        for root_enum in root_enums {
            self.line(format!("    {},", root_enum.name));
        }
        self.line("}");
        self.blank();
        self.emit_schema_plane_support();
        self.blank();
        self.emit_plane_envelope("Signal");
        self.blank();
        self.emit_plane_envelope("Nexus");
        self.blank();
        self.emit_plane_envelope("Sema");
        self.blank();
        self.line("#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]");
        self.line("pub struct MessageSent {");
        self.line("    pub identifier: MessageIdentifier,");
        self.line("    pub origin_route: OriginRoute,");
        self.line("    pub root: MessageRoot,");
        self.line("    pub short_header: Integer,");
        self.line("}");
        self.blank();
        self.line("#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]");
        self.line("pub struct NexusMail<Payload> {");
        self.line("    pub identifier: MessageIdentifier,");
        self.line("    pub origin_route: OriginRoute,");
        self.line("    pub payload: Payload,");
        self.line("}");
        self.blank();
        self.line("#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]");
        self.line("pub struct MessageProcessed<Reply> {");
        self.line("    pub identifier: MessageIdentifier,");
        self.line("    pub origin_route: OriginRoute,");
        self.line("    pub reply: Reply,");
        self.line("}");
        self.blank();
        self.line("pub trait MessageSentHook {");
        self.line("    type Error;");
        self.blank();
        self.line("    fn message_sent(&mut self, event: MessageSent) -> Result<(), Self::Error>;");
        self.line("}");
        self.blank();
        self.line("pub trait MessageProcessedHook<Reply> {");
        self.line("    type Error;");
        self.blank();
        self.line("    fn message_processed(&mut self, event: MessageProcessed<Reply>) -> Result<(), Self::Error>;");
        self.line("}");
        self.blank();
        self.line("impl MessageSent {");
        self.line("    pub fn origin_route(&self) -> OriginRoute {");
        self.line("        self.origin_route");
        self.line("    }");
        self.blank();
        self.line("    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>");
        self.line("    where");
        self.line("        Hook: MessageSentHook,");
        self.line("    {");
        self.line("        hook.message_sent(self.clone())");
        self.line("    }");
        self.line("}");
        self.blank();
        self.line("impl<Payload> NexusMail<Payload> {");
        self.line("    pub fn new(identifier: MessageIdentifier, origin_route: OriginRoute, payload: Payload) -> Self {");
        self.line("        Self { identifier, origin_route, payload }");
        self.line("    }");
        self.blank();
        self.line("    pub fn identifier(&self) -> MessageIdentifier {");
        self.line("        self.identifier");
        self.line("    }");
        self.blank();
        self.line("    pub fn origin_route(&self) -> OriginRoute {");
        self.line("        self.origin_route");
        self.line("    }");
        self.blank();
        self.line("    pub fn into_payload(self) -> Payload {");
        self.line("        self.payload");
        self.line("    }");
        self.line("}");
        self.blank();
        self.line("impl<Reply> MessageProcessed<Reply> {");
        self.line("    pub fn new(identifier: MessageIdentifier, origin_route: OriginRoute, reply: Reply) -> Self {");
        self.line("        Self { identifier, origin_route, reply }");
        self.line("    }");
        self.blank();
        self.line("    pub fn identifier(&self) -> MessageIdentifier {");
        self.line("        self.identifier");
        self.line("    }");
        self.blank();
        self.line("    pub fn origin_route(&self) -> OriginRoute {");
        self.line("        self.origin_route");
        self.line("    }");
        self.blank();
        self.line("    pub fn into_reply(self) -> Reply {");
        self.line("        self.reply");
        self.line("    }");
        self.blank();
        self.line("    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>");
        self.line("    where");
        self.line("        Hook: MessageProcessedHook<Reply>,");
        self.line("        Reply: Clone,");
        self.line("    {");
        self.line("        hook.message_processed(self.clone())");
        self.line("    }");
        self.line("}");
        self.blank();
        for root_enum in root_enums {
            self.line(format!("impl {} {{", root_enum.name));
            self.line(
                "    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {",
            );
            self.line("        Signal::new(origin_route, self)");
            self.line("    }");
            self.blank();
            self.line("}");
            self.blank();
            self.line(format!("impl signal::Signal<{}> {{", root_enum.name));
            self.line(
                "    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {",
            );
            self.line("        MessageSent {");
            self.line("            identifier,");
            self.line("            origin_route: self.origin_route(),");
            self.line(format!(
                "            root: MessageRoot::{},",
                root_enum.name
            ));
            self.line("            short_header: self.root().short_header(),");
            self.line("        }");
            self.line("    }");
            self.line("}");
            self.blank();
        }
    }

    fn emit_schema_plane_support(&mut self) {
        self.line("pub mod schema {");
        self.line("    #[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]");
        self.line("    pub enum Plane<SignalRoot, NexusRoot, SemaRoot> {");
        self.line("        Signal(super::Signal<SignalRoot>),");
        self.line("        Nexus(super::Nexus<NexusRoot>),");
        self.line("        Sema(super::Sema<SemaRoot>),");
        self.line("    }");
        self.blank();
        self.line(
            "    impl<SignalRoot, NexusRoot, SemaRoot> Plane<SignalRoot, NexusRoot, SemaRoot> {",
        );
        self.line("        pub fn origin_route(&self) -> super::OriginRoute {");
        self.line("            match self {");
        self.line("                Self::Signal(message) => message.origin_route(),");
        self.line("                Self::Nexus(message) => message.origin_route(),");
        self.line("                Self::Sema(message) => message.origin_route(),");
        self.line("            }");
        self.line("        }");
        self.line("    }");
        self.line("}");
    }

    fn emit_plane_envelope(&mut self, name: &str) {
        self.line("#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]");
        self.line(format!("pub struct {name}<Root> {{"));
        self.line("    pub origin_route: OriginRoute,");
        self.line("    pub root: Root,");
        self.line("}");
        self.blank();
        self.line(format!("impl<Root> {name}<Root> {{"));
        self.line("    pub fn new(origin_route: OriginRoute, root: Root) -> Self {");
        self.line("        Self { origin_route, root }");
        self.line("    }");
        self.blank();
        self.line("    pub fn origin_route(&self) -> OriginRoute {");
        self.line("        self.origin_route");
        self.line("    }");
        self.blank();
        self.line("    pub fn root(&self) -> &Root {");
        self.line("        &self.root");
        self.line("    }");
        self.blank();
        self.line("    pub fn into_root(self) -> Root {");
        self.line("        self.root");
        self.line("    }");
        self.blank();
        self.line(format!("    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> {name}<NextRoot> {{"));
        self.line(format!(
            "        {name}::new(self.origin_route, map(self.root))"
        ));
        self.line("    }");
        self.line("}");
    }

    fn emit_plane_namespaces(
        &mut self,
        declarations: &[TypeDeclaration],
        root_enums: &[&EnumDeclaration],
    ) {
        if self.has_root_enum(root_enums, "Input") || self.has_root_enum(root_enums, "Output") {
            self.line("pub mod signal {");
            if self.has_root_enum(root_enums, "Input") {
                self.line("    pub type Input = super::Input;");
            }
            if self.has_root_enum(root_enums, "Output") {
                self.line("    pub type Output = super::Output;");
            }
            self.line("    pub type Signal<Root> = super::Signal<Root>;");
            self.line("}");
            self.blank();
        }
        if self.has_type(declarations, "NexusInput") || self.has_type(declarations, "NexusOutput") {
            self.line("pub mod nexus {");
            if self.has_type(declarations, "NexusInput") {
                self.line("    pub type Input = super::NexusInput;");
            }
            if self.has_type(declarations, "NexusOutput") {
                self.line("    pub type Output = super::NexusOutput;");
            }
            self.line("    pub type Nexus<Root> = super::Nexus<Root>;");
            self.line("}");
            self.blank();
        }
        if self.has_type(declarations, "SemaInput") || self.has_type(declarations, "SemaOutput") {
            self.line("pub mod sema {");
            if self.has_type(declarations, "SemaInput") {
                self.line("    pub type Input = super::SemaInput;");
            }
            if self.has_type(declarations, "SemaOutput") {
                self.line("    pub type Output = super::SemaOutput;");
            }
            self.line("    pub type Sema<Root> = super::Sema<Root>;");
            self.line("}");
            self.blank();
        }
        if self.has_type(declarations, "NexusInput") {
            self.emit_plane_origin_route_constructor("NexusInput", "nexus::Nexus", "nexus::Nexus");
        }
        if self.has_type(declarations, "NexusOutput") {
            self.emit_plane_origin_route_constructor("NexusOutput", "nexus::Nexus", "nexus::Nexus");
        }
        if self.has_type(declarations, "SemaInput") {
            self.emit_plane_origin_route_constructor("SemaInput", "sema::Sema", "sema::Sema");
        }
        if self.has_type(declarations, "SemaOutput") {
            self.emit_plane_origin_route_constructor("SemaOutput", "sema::Sema", "sema::Sema");
        }
    }

    fn emit_plane_origin_route_constructor(
        &mut self,
        type_name: &str,
        return_type: &str,
        constructor: &str,
    ) {
        self.line(format!("impl {type_name} {{"));
        self.line(format!(
            "    pub fn with_origin_route(self, origin_route: OriginRoute) -> {return_type}<Self> {{"
        ));
        self.line(format!("        {constructor}::new(origin_route, self)"));
        self.line("    }");
        self.line("}");
        self.blank();
    }

    fn emit_nexus_support(&mut self, root_enums: &[&EnumDeclaration]) {
        for root_enum in root_enums {
            self.emit_nexus_trait(root_enum);
            self.blank();
            self.emit_nexus_dispatch_impl(root_enum);
            self.blank();
        }
    }

    fn emit_nexus_trait(&mut self, root_enum: &EnumDeclaration) {
        let trait_name = format!("{}Nexus", root_enum.name);
        self.line(format!("pub trait {trait_name} {{"));
        self.line("    type Reply;");
        self.line("    type Error;");
        self.blank();
        for variant in &root_enum.variants {
            let method_name = variant.name.field_name();
            match &variant.payload {
                Some(payload) => self.line(format!(
                    "    fn {method_name}(&self, mail: NexusMail<{}>) -> Result<Self::Reply, Self::Error>;",
                    self.rust_type(payload)
                )),
                None => self.line(format!(
                    "    fn {method_name}(&self, mail: NexusMail<()>) -> Result<Self::Reply, Self::Error>;"
                )),
            }
        }
        self.line("}");
    }

    fn emit_nexus_dispatch_impl(&mut self, root_enum: &EnumDeclaration) {
        let trait_name = format!("{}Nexus", root_enum.name);
        self.line(format!("impl {} {{", root_enum.name));
        self.line("    pub fn dispatch_mail_with_nexus<NexusActor>(self, identifier: MessageIdentifier, origin_route: OriginRoute, nexus: &NexusActor) -> Result<MessageProcessed<NexusActor::Reply>, NexusActor::Error>");
        self.line("    where");
        self.line(format!("        NexusActor: {trait_name},"));
        self.line("    {");
        self.line("        let reply = match self {");
        for variant in &root_enum.variants {
            let method_name = variant.name.field_name();
            match &variant.payload {
                Some(_) => self.line(format!(
                    "            Self::{}(payload) => nexus.{method_name}(NexusMail::new(identifier, origin_route, payload)),",
                    variant.name
                )),
                None => self.line(format!(
                    "            Self::{} => nexus.{method_name}(NexusMail::new(identifier, origin_route, ())),",
                    variant.name
                )),
            }
        }
        self.line("        }?;");
        self.line("        Ok(MessageProcessed::new(identifier, origin_route, reply))");
        self.line("    }");
        self.line("}");
    }

    fn emit_upgrade_support(&mut self) {
        self.line("pub trait UpgradeFrom<Previous>: Sized {");
        self.line("    type Error;");
        self.blank();
        self.line("    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;");
        self.line("}");
        self.blank();
        self.line("pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {");
        self.line("    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {");
        self.line("        Self::upgrade_from(previous)");
        self.line("    }");
        self.line("}");
        self.blank();
        self.line("impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}");
    }

    fn emit_schema_plane_trait_support(&mut self, declarations: &[TypeDeclaration]) {
        if self.has_type(declarations, "NexusInput") && self.has_type(declarations, "NexusOutput") {
            self.line("pub trait NexusEngine {");
            self.line("    fn execute(&self, input: nexus::Nexus<nexus::Input>) -> nexus::Nexus<nexus::Output>;");
            self.line("}");
            self.blank();
        }
        if self.has_type(declarations, "SemaInput") && self.has_type(declarations, "SemaOutput") {
            self.line("pub trait SemaEngine {");
            self.line("    fn apply(&mut self, input: sema::Sema<sema::Input>) -> sema::Sema<sema::Output>;");
            self.line("}");
            self.blank();
        }
    }

    fn has_root_enum(&self, root_enums: &[&EnumDeclaration], type_name: &str) -> bool {
        root_enums
            .iter()
            .any(|declaration| declaration.name.as_str() == type_name)
    }

    fn has_type(&self, declarations: &[TypeDeclaration], type_name: &str) -> bool {
        declarations
            .iter()
            .any(|declaration| self.type_name(declaration).as_str() == type_name)
    }

    fn type_name(&self, declaration: &TypeDeclaration) -> Name {
        match declaration {
            TypeDeclaration::Struct(declaration) | TypeDeclaration::Newtype(declaration) => {
                declaration.name.clone()
            }
            TypeDeclaration::Enum(declaration) => declaration.name.clone(),
        }
    }

    /// The Rust type for a reference.
    ///
    /// Scalar leaves map to emitted scalar aliases. A plain declared-name
    /// leaf maps to its local or imported type name. The
    /// collection variants recurse: `Vector` → `Vec<inner>`, `Map` →
    /// `BTreeMap<key, value>` (the `KeyValue` keyword), `Optional` →
    /// `Option<inner>`. `BTreeMap` is written fully-qualified so no
    /// `use` is emitted and the ordering is deterministic (rkyv + NOTA
    /// round-trips need a stable key order).
    fn rust_type(&self, reference: &TypeReference) -> String {
        match reference {
            TypeReference::String => "String".to_owned(),
            TypeReference::Integer => "Integer".to_owned(),
            TypeReference::Boolean => "Boolean".to_owned(),
            TypeReference::Path => "Path".to_owned(),
            TypeReference::Plain(name) => name.as_str().to_owned(),
            TypeReference::Vector(inner) => format!("Vec<{}>", self.rust_type(inner)),
            TypeReference::Map(key, value) => format!(
                "std::collections::BTreeMap<{}, {}>",
                self.rust_type(key),
                self.rust_type(value)
            ),
            TypeReference::Optional(inner) => format!("Option<{}>", self.rust_type(inner)),
        }
    }

    fn constant_name(&self, name: &Name) -> String {
        let mut output = String::new();
        for (index, character) in name.as_str().chars().enumerate() {
            if character.is_ascii_uppercase() {
                if index > 0 {
                    output.push('_');
                }
                output.push(character);
            } else if character == '-' {
                output.push('_');
            } else {
                output.push(character.to_ascii_uppercase());
            }
        }
        output
    }
}
