//! Designer 481 — migration code emission from `UpgradeObject`.
//!
//! Given an `UpgradeObject` from `schema-next`, the emitter produces a
//! Rust module containing:
//!
//!  - `mod historical` — the previous-version field shape needed to read
//!    archived records (the pilot keeps this narrow: only the fields the
//!    upgrade actually touches need typed historical mirrors).
//!  - `mod current` — the next-version field shape.
//!  - `impl From<historical::T> for current::T` — typed projection per
//!    schema-edit, materializing the `FieldMigration` directive.
//!
//! Per designer 447 §"Block 3" (the MigrationEmitter): the emission
//! pattern (`mod historical` + `mod current` + `From`-chain) generalizes
//! the workspace's existing hand-written migration shape
//! (`skills/spirit-cli.md` §"Substrate migration discipline") into
//! schema-derivable code.
//!
//! The pilot covers the three operations the witness test asserts:
//! `AddField` with `DefaultValue::Integer`, `ChangeFieldType` with
//! `FieldMigration::WrapSingleton`, and `AddVariant` on an enum.

use schema_next::{
    AddField, AddVariant, ChangeFieldType, DefaultValue, FieldMigration, Name, SchemaEdit,
    TypeReference, UpgradeObject,
};

/// The emitter for upgrade/compatibility code derived from an
/// `UpgradeObject`. The data-bearing noun holds the upgrade object the
/// emitter is rendering against; the `emit` method produces the Rust
/// source string.
#[derive(Clone, Debug)]
pub struct MigrationEmitter<'upgrade> {
    upgrade: &'upgrade UpgradeObject,
}

impl<'upgrade> MigrationEmitter<'upgrade> {
    pub fn new(upgrade: &'upgrade UpgradeObject) -> Self {
        Self { upgrade }
    }

    pub fn upgrade(&self) -> &UpgradeObject {
        self.upgrade
    }

    /// Render the migration source. The output is a complete Rust module
    /// body, ready to be written to a file or embedded inside a parent
    /// module.
    pub fn emit(&self) -> String {
        let mut writer = MigrationWriter::new(self.upgrade);
        writer.write_header();
        writer.write_historical_module();
        writer.write_current_module();
        writer.write_projection_impls();
        writer.into_string()
    }
}

/// Builder noun owning the rendered string. Each public `write_*` method
/// appends a section.
struct MigrationWriter<'upgrade> {
    upgrade: &'upgrade UpgradeObject,
    output: String,
    targets: Vec<MigrationTarget>,
}

impl<'upgrade> MigrationWriter<'upgrade> {
    fn new(upgrade: &'upgrade UpgradeObject) -> Self {
        let targets = MigrationTarget::from_upgrade(upgrade);
        Self {
            upgrade,
            output: String::new(),
            targets,
        }
    }

    fn into_string(self) -> String {
        self.output
    }

    fn write_header(&mut self) {
        let previous = self.upgrade.previous_identity();
        let next = self.upgrade.next_identity();
        self.line("// @generated by schema-rust-next (designer 481 pilot)");
        self.line(&format!(
            "// upgrade: {}@{} -> {}@{}",
            previous.component().as_str(),
            previous.version(),
            next.component().as_str(),
            next.version()
        ));
        self.blank();
    }

    fn write_historical_module(&mut self) {
        self.line("pub mod historical {");
        for target in &self.targets {
            target.write_historical(&mut self.output);
        }
        self.line("}");
        self.blank();
    }

    fn write_current_module(&mut self) {
        self.line("pub mod current {");
        for target in &self.targets {
            target.write_current(&mut self.output);
        }
        self.line("}");
        self.blank();
    }

    fn write_projection_impls(&mut self) {
        for target in &self.targets {
            target.write_projection(&mut self.output);
        }
    }

    fn line(&mut self, line: &str) {
        self.output.push_str(line);
        self.output.push('\n');
    }

    fn blank(&mut self) {
        self.output.push('\n');
    }
}

/// One migration target — a struct or enum the upgrade touched. Built
/// from the per-edit operations the upgrade carries.
#[derive(Clone, Debug)]
enum MigrationTarget {
    Struct(MigrationStructTarget),
    Enum(MigrationEnumTarget),
}

impl MigrationTarget {
    fn from_upgrade(upgrade: &UpgradeObject) -> Vec<Self> {
        let mut targets: Vec<MigrationTarget> = Vec::new();
        for edit in upgrade.edits() {
            match edit {
                SchemaEdit::AddField(operation) => {
                    let target = Self::find_or_insert_struct(&mut targets, &operation.target_type);
                    target.absorb_add_field(operation);
                }
                SchemaEdit::ChangeFieldType(operation) => {
                    let target = Self::find_or_insert_struct(&mut targets, &operation.target_type);
                    target.absorb_change_field_type(operation);
                }
                SchemaEdit::AddVariant(operation) => {
                    let target = Self::find_or_insert_enum(&mut targets, &operation.target_type);
                    target.absorb_add_variant(operation);
                }
            }
        }
        targets
    }

    fn find_or_insert_struct<'targets>(
        targets: &'targets mut Vec<MigrationTarget>,
        name: &Name,
    ) -> &'targets mut MigrationStructTarget {
        let position = targets.iter().position(|target| match target {
            MigrationTarget::Struct(structure) => &structure.name == name,
            MigrationTarget::Enum(_) => false,
        });
        let index = match position {
            Some(index) => index,
            None => {
                targets.push(MigrationTarget::Struct(MigrationStructTarget::new(
                    name.clone(),
                )));
                targets.len() - 1
            }
        };
        match &mut targets[index] {
            MigrationTarget::Struct(structure) => structure,
            MigrationTarget::Enum(_) => unreachable!("position matched a struct"),
        }
    }

    fn find_or_insert_enum<'targets>(
        targets: &'targets mut Vec<MigrationTarget>,
        name: &Name,
    ) -> &'targets mut MigrationEnumTarget {
        let position = targets.iter().position(|target| match target {
            MigrationTarget::Enum(enumeration) => &enumeration.name == name,
            MigrationTarget::Struct(_) => false,
        });
        let index = match position {
            Some(index) => index,
            None => {
                targets.push(MigrationTarget::Enum(MigrationEnumTarget::new(
                    name.clone(),
                )));
                targets.len() - 1
            }
        };
        match &mut targets[index] {
            MigrationTarget::Enum(enumeration) => enumeration,
            MigrationTarget::Struct(_) => unreachable!("position matched an enum"),
        }
    }

    fn write_historical(&self, output: &mut String) {
        match self {
            Self::Struct(structure) => structure.write_historical(output),
            Self::Enum(enumeration) => enumeration.write_historical(output),
        }
    }

    fn write_current(&self, output: &mut String) {
        match self {
            Self::Struct(structure) => structure.write_current(output),
            Self::Enum(enumeration) => enumeration.write_current(output),
        }
    }

    fn write_projection(&self, output: &mut String) {
        match self {
            Self::Struct(structure) => structure.write_projection(output),
            Self::Enum(enumeration) => enumeration.write_projection(output),
        }
    }
}

#[derive(Clone, Debug)]
struct MigrationStructTarget {
    name: Name,
    field_actions: Vec<FieldAction>,
}

impl MigrationStructTarget {
    fn new(name: Name) -> Self {
        Self {
            name,
            field_actions: Vec::new(),
        }
    }

    fn absorb_add_field(&mut self, operation: &AddField) {
        self.field_actions.push(FieldAction::Added {
            name: operation.field_name.clone(),
            field_type: operation.field_type.clone(),
            default: operation.default_value.clone(),
        });
    }

    fn absorb_change_field_type(&mut self, operation: &ChangeFieldType) {
        self.field_actions.push(FieldAction::Changed {
            name: operation.field_name.clone(),
            new_type: operation.new_type.clone(),
            migration: operation.migration.clone(),
        });
    }

    fn write_historical(&self, output: &mut String) {
        Indenter::new(output).push(1);
        output.push_str(&format!("pub struct {} {{\n", self.name.as_str()));
        for action in &self.field_actions {
            if let Some((field_name, field_type)) = action.historical_field() {
                Indenter::new(output).push(2);
                output.push_str(&format!(
                    "pub {}: {},\n",
                    field_name,
                    TypeRenderer::new(&field_type).render()
                ));
            }
        }
        Indenter::new(output).push(1);
        output.push_str("}\n\n");
    }

    fn write_current(&self, output: &mut String) {
        Indenter::new(output).push(1);
        output.push_str(&format!("pub struct {} {{\n", self.name.as_str()));
        for action in &self.field_actions {
            let (field_name, field_type) = action.current_field();
            Indenter::new(output).push(2);
            output.push_str(&format!(
                "pub {}: {},\n",
                field_name,
                TypeRenderer::new(&field_type).render()
            ));
        }
        Indenter::new(output).push(1);
        output.push_str("}\n\n");
    }

    fn write_projection(&self, output: &mut String) {
        output.push_str(&format!(
            "impl From<historical::{name}> for current::{name} {{\n",
            name = self.name.as_str()
        ));
        Indenter::new(output).push(1);
        output.push_str(&format!(
            "fn from(previous: historical::{}) -> Self {{\n",
            self.name.as_str()
        ));
        Indenter::new(output).push(2);
        output.push_str("Self {\n");
        for action in &self.field_actions {
            Indenter::new(output).push(3);
            output.push_str(&action.projection_line());
            output.push('\n');
        }
        Indenter::new(output).push(2);
        output.push_str("}\n");
        Indenter::new(output).push(1);
        output.push_str("}\n}\n\n");
    }
}

#[derive(Clone, Debug)]
struct MigrationEnumTarget {
    name: Name,
    added_variants: Vec<AddedVariant>,
}

impl MigrationEnumTarget {
    fn new(name: Name) -> Self {
        Self {
            name,
            added_variants: Vec::new(),
        }
    }

    fn absorb_add_variant(&mut self, operation: &AddVariant) {
        self.added_variants.push(AddedVariant {
            name: operation.variant_name.clone(),
            payload: operation.payload.clone(),
        });
    }

    fn write_historical(&self, output: &mut String) {
        Indenter::new(output).push(1);
        output.push_str(&format!("pub enum {} {{}}\n\n", self.name.as_str()));
    }

    fn write_current(&self, output: &mut String) {
        Indenter::new(output).push(1);
        output.push_str(&format!("pub enum {} {{\n", self.name.as_str()));
        for variant in &self.added_variants {
            Indenter::new(output).push(2);
            match &variant.payload {
                Some(payload) => output.push_str(&format!(
                    "{}({}),\n",
                    variant.name.as_str(),
                    TypeRenderer::new(payload).render()
                )),
                None => output.push_str(&format!("{},\n", variant.name.as_str())),
            }
        }
        Indenter::new(output).push(1);
        output.push_str("}\n\n");
    }

    fn write_projection(&self, output: &mut String) {
        // The historical enum is uninhabited (no variants) — the
        // projection function below has no historical input to dispatch
        // on, so we generate a `match previous {}` that the compiler
        // accepts because the enum carries no variants.
        output.push_str(&format!(
            "impl From<historical::{name}> for current::{name} {{\n",
            name = self.name.as_str()
        ));
        Indenter::new(output).push(1);
        output.push_str(&format!(
            "fn from(previous: historical::{}) -> Self {{\n",
            self.name.as_str()
        ));
        Indenter::new(output).push(2);
        output.push_str("match previous {}\n");
        Indenter::new(output).push(1);
        output.push_str("}\n}\n\n");
    }
}

#[derive(Clone, Debug)]
enum FieldAction {
    Added {
        name: Name,
        field_type: TypeReference,
        default: DefaultValue,
    },
    Changed {
        name: Name,
        new_type: TypeReference,
        migration: FieldMigration,
    },
}

impl FieldAction {
    /// Return the historical-mirror field for this action, when the
    /// historical record needs to carry the field. For `Added`, the
    /// historical record does NOT carry the field (the field was added,
    /// after all); the projection line minted the default value. For
    /// `Changed`, the historical record DOES carry the previous type;
    /// the new type comes in only on the current side.
    fn historical_field(&self) -> Option<(String, TypeReference)> {
        match self {
            Self::Added { .. } => None,
            Self::Changed { name, .. } => Some((name.field_name(), self.previous_type())),
        }
    }

    /// The inferred previous-type of a changed field, derived from the
    /// new type and the migration directive. `WrapSingleton` strips the
    /// `Vec<T>` wrapper to recover `T`; `SetDefault` keeps the new type
    /// (the type was unchanged, only the default-fill behaviour shifted).
    /// For `Added`, the previous type is by convention the new field
    /// type, since the migration generates a default from the directive
    /// rather than reading a historical value.
    fn previous_type(&self) -> TypeReference {
        match self {
            Self::Changed {
                new_type,
                migration,
                ..
            } => match migration {
                FieldMigration::WrapSingleton => match new_type {
                    TypeReference::Vector(inner) => (**inner).clone(),
                    other => other.clone(),
                },
                FieldMigration::SetDefault(_) => new_type.clone(),
            },
            Self::Added { field_type, .. } => field_type.clone(),
        }
    }

    fn current_field(&self) -> (String, TypeReference) {
        match self {
            Self::Added {
                name, field_type, ..
            } => (name.field_name(), field_type.clone()),
            Self::Changed { name, new_type, .. } => (name.field_name(), new_type.clone()),
        }
    }

    fn projection_line(&self) -> String {
        match self {
            Self::Added { name, default, .. } => format!(
                "{name}: {literal},",
                name = name.field_name(),
                literal = DefaultRenderer::new(default).render()
            ),
            Self::Changed {
                name, migration, ..
            } => match migration {
                FieldMigration::WrapSingleton => {
                    format!("{name}: vec![previous.{name}],", name = name.field_name())
                }
                FieldMigration::SetDefault(default) => format!(
                    "{name}: {literal},",
                    name = name.field_name(),
                    literal = DefaultRenderer::new(default).render()
                ),
            },
        }
    }
}

#[derive(Clone, Debug)]
struct AddedVariant {
    name: Name,
    payload: Option<TypeReference>,
}

/// Render a `TypeReference` as the Rust source string the emitter writes
/// into the migration module. The renderer is a thin data-bearing
/// wrapper over the foreign `TypeReference` from schema-next, so the
/// verb still belongs to a noun even though the inner type lives in a
/// different crate.
#[derive(Clone, Copy, Debug)]
pub struct TypeRenderer<'reference> {
    reference: &'reference TypeReference,
}

impl<'reference> TypeRenderer<'reference> {
    pub fn new(reference: &'reference TypeReference) -> Self {
        Self { reference }
    }

    pub fn render(&self) -> String {
        match self.reference {
            TypeReference::String => "String".to_owned(),
            TypeReference::Integer => "i64".to_owned(),
            TypeReference::Boolean => "bool".to_owned(),
            TypeReference::Path => "String".to_owned(),
            TypeReference::Plain(name) => name.as_str().to_owned(),
            TypeReference::Vector(inner) => format!("Vec<{}>", TypeRenderer::new(inner).render()),
            TypeReference::Optional(inner) => {
                format!("Option<{}>", TypeRenderer::new(inner).render())
            }
            TypeReference::Map(key, value) => format!(
                "std::collections::HashMap<{}, {}>",
                TypeRenderer::new(key).render(),
                TypeRenderer::new(value).render()
            ),
        }
    }
}

/// Render a `DefaultValue` as the Rust literal expression that fills the
/// field on projection. Same shape as `TypeRenderer` — a data-bearing
/// wrapper that keeps the rendering verb attached to a noun.
#[derive(Clone, Copy, Debug)]
pub struct DefaultRenderer<'default> {
    default: &'default DefaultValue,
}

impl<'default> DefaultRenderer<'default> {
    pub fn new(default: &'default DefaultValue) -> Self {
        Self { default }
    }

    pub fn render(&self) -> String {
        match self.default {
            DefaultValue::Integer(value) => format!("{value}_i64"),
            DefaultValue::String(value) => format!("String::from({value:?})"),
            DefaultValue::Boolean(value) => value.to_string(),
            DefaultValue::Unit => "()".to_owned(),
        }
    }
}

/// Indenter — owns the buffer it pushes into and the indent depth. Keeps
/// the indenting verb on the buffer-bearing noun rather than as a free
/// helper.
#[derive(Debug)]
struct Indenter<'output> {
    output: &'output mut String,
}

impl<'output> Indenter<'output> {
    fn new(output: &'output mut String) -> Self {
        Self { output }
    }

    fn push(&mut self, levels: usize) {
        for _ in 0..levels {
            self.output.push_str("    ");
        }
    }
}
