//! Designer 481 — migration code emission from `UpgradeObject`.
//!
//! Given an `UpgradeObject` from `schema-next`, the emitter produces a
//! Rust module containing:
//!
//!  - `mod historical` — the previous-version field shape needed to read
//!    archived records (the pilot keeps this narrow: only the fields the
//!    upgrade actually touches need typed historical mirrors).
//!  - `mod current` — the next-version field shape.
//!  - `impl From<historical::T> for current::T` — typed projection per
//!    schema-edit, materializing the `FieldMigration` directive.
//!
//! Per designer 447 §"Block 3" (the MigrationEmitter): the emission
//! pattern (`mod historical` + `mod current` + `From`-chain) generalizes
//! the workspace's existing hand-written migration shape
//! (`skills/spirit-cli.md` §"Substrate migration discipline") into
//! schema-derivable code.
//!
//! The pilot covers the three operations the witness test asserts:
//! `AddField` with `DefaultValue::Integer`, `ChangeFieldType` with
//! `FieldMigration::WrapSingleton`, and `AddVariant` on an enum.
//!
//! Rust syntax is built as `proc_macro2` token streams through `quote!`
//! and pretty-printed once at the boundary, matching the token-first
//! discipline of the main emitter (`lib.rs`). The `// @generated` header
//! is prepended as text because `prettyplease` does not preserve
//! non-doc comments through a parse/unparse round-trip.

use proc_macro2::{Ident, Span, TokenStream};
use quote::{ToTokens, quote};
use schema_next::{
    AddField, AddVariant, ChangeFieldType, DefaultValue, FieldMigration, Name, SchemaEdit,
    TypeReference, UpgradeObject,
};

use crate::RustfmtSkippedItems;

/// The emitter for upgrade/compatibility code derived from an
/// `UpgradeObject`. The data-bearing noun holds the upgrade object the
/// emitter is rendering against; the `emit` method produces the Rust
/// source string.
#[derive(Clone, Debug)]
pub struct MigrationEmitter<'upgrade> {
    upgrade: &'upgrade UpgradeObject,
}

impl<'upgrade> MigrationEmitter<'upgrade> {
    pub fn new(upgrade: &'upgrade UpgradeObject) -> Self {
        Self { upgrade }
    }

    pub fn upgrade(&self) -> &UpgradeObject {
        self.upgrade
    }

    /// Render the migration source. The output is a complete Rust module
    /// body, ready to be written to a file or embedded inside a parent
    /// module.
    pub fn emit(&self) -> String {
        let module = MigrationModule::new(self.upgrade);
        let mut source = module.header();
        source.push('\n');
        let body = syn::parse2::<syn::File>(module.body_tokens())
            .expect("generated migration tokens parse");
        source.push_str(&RustfmtSkippedItems::new(body).render());
        source
    }
}

/// The whole migration module derived from an `UpgradeObject`: the
/// `// @generated` header text plus the `historical` / `current` modules
/// and the `From` projection impls as token streams.
struct MigrationModule<'upgrade> {
    upgrade: &'upgrade UpgradeObject,
    targets: Vec<MigrationTarget>,
}

impl<'upgrade> MigrationModule<'upgrade> {
    fn new(upgrade: &'upgrade UpgradeObject) -> Self {
        let targets = MigrationTarget::from_upgrade(upgrade);
        Self { upgrade, targets }
    }

    /// The generated-file header. Kept as text because `prettyplease` drops
    /// non-doc comments.
    fn header(&self) -> String {
        let previous = self.upgrade.previous_identity();
        let next = self.upgrade.next_identity();
        format!(
            "// @generated by schema-rust-next (designer 481 pilot)\n// upgrade: {}@{} -> {}@{}\n",
            previous.component().as_str(),
            previous.version(),
            next.component().as_str(),
            next.version()
        )
    }

    fn body_tokens(&self) -> TokenStream {
        let historical = self.targets.iter().map(MigrationTarget::historical_tokens);
        let current = self.targets.iter().map(MigrationTarget::current_tokens);
        let projections = self.targets.iter().map(MigrationTarget::projection_tokens);
        quote! {
            pub mod historical {
                #(#historical)*
            }
            pub mod current {
                #(#current)*
            }
            #(#projections)*
        }
    }
}

/// One migration target — a struct or enum the upgrade touched. Built
/// from the per-edit operations the upgrade carries.
#[derive(Clone, Debug)]
enum MigrationTarget {
    Struct(MigrationStructTarget),
    Enum(MigrationEnumTarget),
}

impl MigrationTarget {
    fn from_upgrade(upgrade: &UpgradeObject) -> Vec<Self> {
        let mut targets: Vec<MigrationTarget> = Vec::new();
        for edit in upgrade.edits() {
            match edit {
                SchemaEdit::AddField(operation) => {
                    let target = Self::find_or_insert_struct(&mut targets, &operation.target_type);
                    target.absorb_add_field(operation);
                }
                SchemaEdit::ChangeFieldType(operation) => {
                    let target = Self::find_or_insert_struct(&mut targets, &operation.target_type);
                    target.absorb_change_field_type(operation);
                }
                SchemaEdit::AddVariant(operation) => {
                    let target = Self::find_or_insert_enum(&mut targets, &operation.target_type);
                    target.absorb_add_variant(operation);
                }
            }
        }
        targets
    }

    fn find_or_insert_struct<'targets>(
        targets: &'targets mut Vec<MigrationTarget>,
        name: &Name,
    ) -> &'targets mut MigrationStructTarget {
        let position = targets.iter().position(|target| match target {
            MigrationTarget::Struct(structure) => &structure.name == name,
            MigrationTarget::Enum(_) => false,
        });
        let index = match position {
            Some(index) => index,
            None => {
                targets.push(MigrationTarget::Struct(MigrationStructTarget::new(
                    name.clone(),
                )));
                targets.len() - 1
            }
        };
        match &mut targets[index] {
            MigrationTarget::Struct(structure) => structure,
            MigrationTarget::Enum(_) => unreachable!("position matched a struct"),
        }
    }

    fn find_or_insert_enum<'targets>(
        targets: &'targets mut Vec<MigrationTarget>,
        name: &Name,
    ) -> &'targets mut MigrationEnumTarget {
        let position = targets.iter().position(|target| match target {
            MigrationTarget::Enum(enumeration) => &enumeration.name == name,
            MigrationTarget::Struct(_) => false,
        });
        let index = match position {
            Some(index) => index,
            None => {
                targets.push(MigrationTarget::Enum(MigrationEnumTarget::new(
                    name.clone(),
                )));
                targets.len() - 1
            }
        };
        match &mut targets[index] {
            MigrationTarget::Enum(enumeration) => enumeration,
            MigrationTarget::Struct(_) => unreachable!("position matched an enum"),
        }
    }

    fn historical_tokens(&self) -> TokenStream {
        match self {
            Self::Struct(structure) => structure.historical_tokens(),
            Self::Enum(enumeration) => enumeration.historical_tokens(),
        }
    }

    fn current_tokens(&self) -> TokenStream {
        match self {
            Self::Struct(structure) => structure.current_tokens(),
            Self::Enum(enumeration) => enumeration.current_tokens(),
        }
    }

    fn projection_tokens(&self) -> TokenStream {
        match self {
            Self::Struct(structure) => structure.projection_tokens(),
            Self::Enum(enumeration) => enumeration.projection_tokens(),
        }
    }
}

#[derive(Clone, Debug)]
struct MigrationStructTarget {
    name: Name,
    field_actions: Vec<FieldAction>,
}

impl MigrationStructTarget {
    fn new(name: Name) -> Self {
        Self {
            name,
            field_actions: Vec::new(),
        }
    }

    fn absorb_add_field(&mut self, operation: &AddField) {
        self.field_actions.push(FieldAction::Added {
            name: operation.field_name.clone(),
            field_type: operation.field_type.clone(),
            default: operation.default_value.clone(),
        });
    }

    fn absorb_change_field_type(&mut self, operation: &ChangeFieldType) {
        self.field_actions.push(FieldAction::Changed {
            name: operation.field_name.clone(),
            new_type: operation.new_type.clone(),
            migration: operation.migration.clone(),
        });
    }

    fn historical_tokens(&self) -> TokenStream {
        let name = Ident::new(self.name.as_str(), Span::call_site());
        let fields = self.field_actions.iter().filter_map(|action| {
            let (field_name, field_type) = action.historical_field()?;
            let field = Ident::new(&field_name, Span::call_site());
            let field_type = TypeRenderer::new(&field_type).into_token_stream();
            Some(quote! { pub #field: #field_type, })
        });
        quote! {
            pub struct #name {
                #(#fields)*
            }
        }
    }

    fn current_tokens(&self) -> TokenStream {
        let name = Ident::new(self.name.as_str(), Span::call_site());
        let fields = self.field_actions.iter().map(|action| {
            let (field_name, field_type) = action.current_field();
            let field = Ident::new(&field_name, Span::call_site());
            let field_type = TypeRenderer::new(&field_type).into_token_stream();
            quote! { pub #field: #field_type, }
        });
        quote! {
            pub struct #name {
                #(#fields)*
            }
        }
    }

    fn projection_tokens(&self) -> TokenStream {
        let name = Ident::new(self.name.as_str(), Span::call_site());
        let assignments = self
            .field_actions
            .iter()
            .map(FieldAction::projection_assignment);
        quote! {
            impl From<historical::#name> for current::#name {
                fn from(previous: historical::#name) -> Self {
                    Self {
                        #(#assignments)*
                    }
                }
            }
        }
    }
}

#[derive(Clone, Debug)]
struct MigrationEnumTarget {
    name: Name,
    added_variants: Vec<AddedVariant>,
}

impl MigrationEnumTarget {
    fn new(name: Name) -> Self {
        Self {
            name,
            added_variants: Vec::new(),
        }
    }

    fn absorb_add_variant(&mut self, operation: &AddVariant) {
        self.added_variants.push(AddedVariant {
            name: operation.variant_name.clone(),
            payload: operation.payload.clone(),
        });
    }

    fn historical_tokens(&self) -> TokenStream {
        let name = Ident::new(self.name.as_str(), Span::call_site());
        quote! {
            pub enum #name {}
        }
    }

    fn current_tokens(&self) -> TokenStream {
        let name = Ident::new(self.name.as_str(), Span::call_site());
        let variants = self.added_variants.iter().map(AddedVariant::variant_tokens);
        quote! {
            pub enum #name {
                #(#variants)*
            }
        }
    }

    fn projection_tokens(&self) -> TokenStream {
        // The historical enum is uninhabited (no variants) — the
        // projection function below has no historical input to dispatch
        // on, so the generated `match previous {}` compiles because the
        // enum carries no variants.
        let name = Ident::new(self.name.as_str(), Span::call_site());
        quote! {
            impl From<historical::#name> for current::#name {
                fn from(previous: historical::#name) -> Self {
                    match previous {}
                }
            }
        }
    }
}

#[derive(Clone, Debug)]
enum FieldAction {
    Added {
        name: Name,
        field_type: TypeReference,
        default: DefaultValue,
    },
    Changed {
        name: Name,
        new_type: TypeReference,
        migration: FieldMigration,
    },
}

impl FieldAction {
    /// Return the historical-mirror field for this action, when the
    /// historical record needs to carry the field. For `Added`, the
    /// historical record does NOT carry the field (the field was added,
    /// after all); the projection line minted the default value. For
    /// `Changed`, the historical record DOES carry the previous type;
    /// the new type comes in only on the current side.
    fn historical_field(&self) -> Option<(String, TypeReference)> {
        match self {
            Self::Added { .. } => None,
            Self::Changed { name, .. } => Some((name.field_name(), self.previous_type())),
        }
    }

    /// The inferred previous-type of a changed field, derived from the
    /// new type and the migration directive. `WrapSingleton` strips the
    /// `Vec<T>` wrapper to recover `T`; `SetDefault` keeps the new type
    /// (the type was unchanged, only the default-fill behaviour shifted).
    /// For `Added`, the previous type is by convention the new field
    /// type, since the migration generates a default from the directive
    /// rather than reading a historical value.
    fn previous_type(&self) -> TypeReference {
        match self {
            Self::Changed {
                new_type,
                migration,
                ..
            } => match migration {
                FieldMigration::WrapSingleton => match new_type {
                    TypeReference::Vector(inner) => (**inner).clone(),
                    other => other.clone(),
                },
                FieldMigration::SetDefault(_) => new_type.clone(),
            },
            Self::Added { field_type, .. } => field_type.clone(),
        }
    }

    fn current_field(&self) -> (String, TypeReference) {
        match self {
            Self::Added {
                name, field_type, ..
            } => (name.field_name(), field_type.clone()),
            Self::Changed { name, new_type, .. } => (name.field_name(), new_type.clone()),
        }
    }

    fn projection_assignment(&self) -> TokenStream {
        match self {
            Self::Added { name, default, .. } => {
                let field = Ident::new(&name.field_name(), Span::call_site());
                let literal = DefaultRenderer::new(default).into_token_stream();
                quote! { #field: #literal, }
            }
            Self::Changed {
                name, migration, ..
            } => {
                let field = Ident::new(&name.field_name(), Span::call_site());
                match migration {
                    FieldMigration::WrapSingleton => {
                        quote! { #field: vec![previous.#field], }
                    }
                    FieldMigration::SetDefault(default) => {
                        let literal = DefaultRenderer::new(default).into_token_stream();
                        quote! { #field: #literal, }
                    }
                }
            }
        }
    }
}

#[derive(Clone, Debug)]
struct AddedVariant {
    name: Name,
    payload: Option<TypeReference>,
}

impl AddedVariant {
    fn variant_tokens(&self) -> TokenStream {
        let name = Ident::new(self.name.as_str(), Span::call_site());
        match &self.payload {
            Some(payload) => {
                let payload = TypeRenderer::new(payload).into_token_stream();
                quote! { #name(#payload), }
            }
            None => quote! { #name, },
        }
    }
}

/// Render a `TypeReference` as the Rust type tokens the emitter writes
/// into the migration module. The renderer is a thin data-bearing
/// wrapper over the foreign `TypeReference` from schema-next, so the
/// verb still belongs to a noun even though the inner type lives in a
/// different crate.
#[derive(Clone, Copy, Debug)]
pub struct TypeRenderer<'reference> {
    reference: &'reference TypeReference,
}

impl<'reference> TypeRenderer<'reference> {
    pub fn new(reference: &'reference TypeReference) -> Self {
        Self { reference }
    }
}

impl ToTokens for TypeRenderer<'_> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        match self.reference {
            TypeReference::String => quote! { String }.to_tokens(tokens),
            TypeReference::Integer => quote! { i64 }.to_tokens(tokens),
            TypeReference::Boolean => quote! { bool }.to_tokens(tokens),
            TypeReference::Path => quote! { String }.to_tokens(tokens),
            TypeReference::Bytes => quote! { Bytes }.to_tokens(tokens),
            TypeReference::FixedBytes(width) => {
                let width = proc_macro2::Literal::u64_unsuffixed(*width);
                quote! { FixedBytes<#width> }.to_tokens(tokens);
            }
            TypeReference::Plain(name) => {
                Ident::new(name.as_str(), Span::call_site()).to_tokens(tokens)
            }
            TypeReference::Vector(inner) => {
                let inner = TypeRenderer::new(inner);
                quote! { Vec<#inner> }.to_tokens(tokens);
            }
            TypeReference::Optional(inner) => {
                let inner = TypeRenderer::new(inner);
                quote! { Option<#inner> }.to_tokens(tokens);
            }
            TypeReference::ScopeOf(inner) => match inner.plain_name() {
                Some(name) => {
                    let name = Ident::new(&format!("{name}Scope"), Span::call_site());
                    quote! { #name }.to_tokens(tokens);
                }
                None => TypeRenderer::new(inner).to_tokens(tokens),
            },
            TypeReference::Map(key, value) => {
                let key = TypeRenderer::new(key);
                let value = TypeRenderer::new(value);
                quote! { std::collections::HashMap<#key, #value> }.to_tokens(tokens);
            }
            TypeReference::Application { head, arguments } => {
                let head = Ident::new(head.name().as_str(), Span::call_site());
                let arguments = arguments.iter().map(TypeRenderer::new);
                quote! { #head<#(#arguments),*> }.to_tokens(tokens);
            }
        }
    }
}

/// Render a `DefaultValue` as the Rust literal expression that fills the
/// field on projection. Same shape as `TypeRenderer` — a data-bearing
/// wrapper that keeps the rendering verb attached to a noun.
#[derive(Clone, Copy, Debug)]
pub struct DefaultRenderer<'default> {
    default: &'default DefaultValue,
}

impl<'default> DefaultRenderer<'default> {
    pub fn new(default: &'default DefaultValue) -> Self {
        Self { default }
    }
}

impl ToTokens for DefaultRenderer<'_> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        match self.default {
            DefaultValue::Integer(value) => {
                let literal = syn::LitInt::new(&format!("{value}_i64"), Span::call_site());
                literal.to_tokens(tokens);
            }
            DefaultValue::String(value) => quote! { String::from(#value) }.to_tokens(tokens),
            DefaultValue::Boolean(value) => {
                let literal = syn::LitBool::new(*value, Span::call_site());
                literal.to_tokens(tokens);
            }
            DefaultValue::Unit => quote! { () }.to_tokens(tokens),
        }
    }
}
